### ISSUE TITLE
Receive Notifications or Setup Triggers when Motion is Detected

### ISSUE THREAD

**Issue by ellisonpatterson** [mrjackyliang/homebridge-adt-pulse#1]
First, thank you so much for making this! It's working right after installation with no issues!

I'm looking at the ADT Pulse motion detectors, and it says within the web interface that it only logs for notable events, not necessarily general motion events? Is this something that can be changed within the system or is this just a limitation of the motion detectors?

What do you think could be done, if anything, or should I call up ADT to see if they can modify the functionality and triggers of the motion detectors (extremely doubtful).

Thanks!

**Comment by mrjackyliang** [comment]
Right now, I'm working on building a better log system (so to split the differences between error, warning, info, and verbose). The plugin has it fixed to `off` right now.

And to answer your question, the motion activity can be logged when it changes but it doesn't exactly query from the ADT Pulse system.

**Comment by ellisonpatterson** [comment]
> And to answer your question, the motion activity can be logged when it changes but it doesn't exactly query from the ADT Pulse system.

So we could potentially use them as general motion triggers for automation? Like when someone enters a room or something similar without the system being armed?

**Comment by mrjackyliang** [comment]
Oh, I misunderstood. I thought you meant the logs showing in Homebridge. You can receive notifications in the Home app, and set up the accessories to act on a trigger using the Shortcuts app with iOS 13.

**Comment by ellisonpatterson** [comment]
Yeah I have been with the system being armed/disarmed, but since there are ADT Motion detectors, I'm asking if they will even be triggered if the system is not armed.

**Comment by mrjackyliang** [comment]
Yes, they will update themselves about every few seconds or so. There maybe a delay when comparing against the ADT Pulse app and they have a much more extensive protocol than this plugin (which relies on ADT Pulse's website).

**Comment by ellisonpatterson** [comment]
Alright thank you for the clarification, I want to at some point setup lights to turn on when motion is detected by this plugin :)

**Comment by mrjackyliang** [comment]
Sure thing! Closing the ticket now!
