### ISSUE TITLE
Door Lock Code and Screenshot

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#10]
<tr>
        <td class="p_whiteBoxMiddleLeft"></td>
        <td class="p_whiteBoxMiddleCenter" align="center">

    <br><span id="status" class="p_boldNormalTextLarge">Currently Locked</span><div><br><input type="button" id="action_button" name="action_button" value="Unlock" alt="Unlock" class="p_btn p_btnLnormal" onclick="doSubmit( '/myhome/17.0.0-71/quickcontrol/serv/RunRRACommand?sat=0351cd6c-bdc5-4f52-926e-ffd9c063e69c&amp;href=rest\/adt\/ui\/client\/door\/door-75\/setLock&amp;value=0' )" onmouseover="javascript:btnHover(this,'L')" onmouseout="javascript:btnNormal(this,'L')" onmousedown="javascript:btnDown(this,'L')" onmouseup="javascript:btnNormal(this,'L')" data-fitlabel="shrink"><style type="text/css">#testSizeaction_button {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizeaction_button" class="p_btn p_btnLnormal">Unlock</div></div><div><br><br><input type="button" id="cancel_button" name="cancel_button" value="Cancel" alt="Cancel" class="p_btn p_btnLnormal" onclick="closeDialog()" onmouseover="javascript:btnHover(this,'L')" onmouseout="javascript:btnNormal(this,'L')" onmousedown="javascript:btnDown(this,'L')" onmouseup="javascript:btnNormal(this,'L')" data-fitlabel="shrink"><style type="text/css">#testSizecancel_button {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizecancel_button" class="p_btn p_btnLnormal">Cancel</div><br></div>

            
        </td>
        <td class="p_whiteBoxMiddleRight"></td>
    </tr>

![image](https://user-images.githubusercontent.com/36968126/70393924-ab334a00-19bd-11ea-8899-352947cb68db.png)

**Comment by mrjackyliang** [comment]
Closed. Refer to issue #8.
