### ISSUE TITLE
Make available modes configurable?

### ISSUE THREAD

**Issue by robmbrooks** [mrjackyliang/homebridge-adt-pulse#100]
### Is your feature request related to a problem? Please describe.
Night mode fails to set on my system, Home, Away and Off all work.

### Describe the solution you'd like:
Would it be possible to have a configuration option that removes night mode, also maybe allow"Home" to be named "Stay" to be consistent with the Pulse app.

### Describe alternatives you've considered:
If lack of "Night" mode is a bug, happy to provide debugging output, but have been using "Stay" overnight with the desired results since the system was installed.

**Comment by mrjackyliang** [comment]
Hmm, interesting. When I tested night mode, it still works. Granted, night mode isn't an official feature in the ADT Pulse online portal. I had to guess my way around the feature.

Also for the renaming of the Home app, that unfortunately isn't controlled by Homebridge. Apple calls Home as Stay, if mapped correctly and that just can't be changed unless you find another app that allows you to rename it (most likely you'd be using a third-party app).

**Comment by robmbrooks** [comment]
I'm looking into Night mode, it appears to be something an installer would configure...

https://www.ackermansecurity.com/blog/home-security-tips/how-to-properly-arm-your-security-system-stay-vs-away-vs-night

I guess the installer skipped this step on our install, I've poked around in the web interface and I don't think it can be configured via the web portal as owner.

**Comment by mrjackyliang** [comment]
Night mode indeed is available, and is configured by an installer.

Night mode is not available on the portal as UI, but I was able to make it work by changing the arm mode to night.

**Comment by robmbrooks** [comment]
Logs on ADT say "Security Panel Armed Night by Robert Brooks - FAILED. Invalid Arm State Change."

**Comment by mrjackyliang** [comment]
> Logs on ADT say "Security Panel Armed Night by Robert Brooks - FAILED. Invalid Arm State Change."

Let me try this when I get home.

**Comment by mrjackyliang** [comment]
Forgot to update this, night mode is working on my end. Closing for now.
