### ISSUE TITLE
Web Portal version message

### ISSUE THREAD

**Issue by DanLysk** [mrjackyliang/homebridge-adt-pulse#103]
Hi Folks, from Hoobs log there is a Web Portal version message... Thought you might like to know. 

Thank you
-Dan 

![CapturFiles](https://github.com/mrjackyliang/homebridge-adt-pulse/assets/100032956/157fc4b9-5c2d-48d7-ad3f-f6526d24f4dd)

**Comment by mrjackyliang** [comment]
Continue on issue #109
