### ISSUE TITLE
Plug in not working. re did the Token also.

### ISSUE THREAD

**Issue by tarunprakashsingh** [mrjackyliang/homebridge-adt-pulse#106]
### Describe the bug:
What do you think the problem relates to?

### Steps to reproduce the bug:
1. Redid the token but still doesnt work.

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

7/25/2023, 4:18:50 PMHOOBSADT PulseWARNING"logLevel" should be a specific number (10, 20, 30, 40, or 50). Defaulting to 30.
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... Security Panel (system-1)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... KITCHEN MOTION (sensor-14)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 1ST FAMILYROOM WINDOW (sensor-6)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 1ST FLOOR SMOKE (sensor-17)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 1ST LIVINGROOM WINDOW (sensor-4)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 2ND DINNING ROOM WINDOW (sensor-13)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 2ND FAMILYROOM WINDOW (sensor-7)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 2ND KITCHEN WINDOW (sensor-9)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 2ND LIVINGROOM WINDOW (sensor-5)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... 3RD KITCHEN WINDOW (sensor-10)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... BACK DOOR (sensor-3)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... BASEMENT SMOKE (sensor-15)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... BASEMENT WINDOW (sensor-18)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... DINNING ROOM WINDOW (sensor-12)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... FRONT DOOR (sensor-1)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... GARAGE DOOR (sensor-2)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... KITCHEN WINDOW (sensor-8)
7/25/2023, 4:18:50 PMHOOBSADT PulseConfiguring cached accessory... LAUNDRY ROOM WINDOW (sensor-11)
7/25/2023, 4:18:50 PMHOOBSADT Pulserunning on linux (arm)
7/25/2023, 4:18:50 PMHOOBSADT Pulsehomebridge-adt-pulse v2.1.7
7/25/2023, 4:18:50 PMHOOBSADT Pulsenode v16.20.1
7/25/2023, 4:18:50 PMHOOBSADT Pulsehomebridge v1.6.0
### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
Continue in issue #109

**Comment by mrjackyliang** [comment]
Continue in issue #109
