### ISSUE TITLE
unhandled rejection: TypeError: Cannot read properties of null (reading 'match’)

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#107]
Mr. Liang, I am suddenly getting the above message on my ADT Pulse bridge, and none of the devices are working. I read this may have to do with ADT Pulse adopting 2 factor authentication on 7/25, but when I try to follow your instructions for this on Google Chrome it doesn't work. No filter box, can't sign in to my account.  I am desperate to get this up and running again. Too many automations triggered by ADT sensors…

Steve

**Comment by mrjackyliang** [comment]
Continue in issue #109
