### ISSUE TITLE
ADT Pulse  path undefined

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#108]
### Describe the bug:
for the last 2 days the ADT pulse plugin is not logging into the ADT pulse portal.  Giving a Response path undefined.  
Using Verbose 50 debugging log.

Been a user for years first time seeing this error.  No changes were made to my network or homebridge.

### Steps to reproduce the bug:
1. Launch Home bridge
2. look at log
### The Apple device you are using:
- Device: iPhone 14 Pro
- OS: 15.6

### Homebridge information:
Homebridge:  V1.6.0
ADT homebridge plugin: homebridge-adt-pulse v2.1.7
Node.js Version | v16.19.0

```sh
[7/28/2023, 12:11:33 PM] Homebridge v1.6.0 (HAP v0.11.0) (ADT-Homebridge) is running on port 51827.
ADT Pulse: Logging in...
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
[7/28/2023, 12:11:33 PM] Homebridge v1.6.0 (HAP v0.11.0) (ADT-Homebridge) is running on port 51827.
ADT Pulse: Logging in...
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.
```

**Comment by mrjackyliang** [comment]
Continue in issue #109
