### ISSUE TITLE
Latest Bug / Issue

### ISSUE THREAD

**Issue by mrjackyliang** [mrjackyliang/homebridge-adt-pulse#109]
can all of you post your portal versions? And your respective errors. I noticed for a while now, specific errors come along with specific versions, and not the same versions are propagated at the same time for everyone (some might use older, some might use newer).

**Comment by sptv1** [comment]
That did the trick for me. Up and working now.

**Comment by cyberpower678** [comment]
A few days ago my connection went down.  Turns out the MFA Fingerprint expired.  At first I thought this didn't work when I added a new one, when I realized I was being bot-blocked by ADT when trying to sign in.  The plugin is exceeding some kind of rate limit on auth failures, which prompts ADT to temporarily ban you IP.  Users trying to reset the Fingerprint will still not be able to get it to work unless they disable the plugin for 15 minutes first.
 
 Once I figured this out, the plugin started working again for me.

**Comment by mrjackyliang** [comment]
Yeah, I could probably add a setting to stop the plugin without resetting it.

**Comment by mrjackyliang** [comment]
Version `2.2.0` is out and adds a pause plugin functionality and updates the currently supported/tested version.

**Comment by mdombrowski13** [comment]
my pulse portal is 26.0.0-32.  Still unable to connect via homebridge.

**Comment by mrjackyliang** [comment]
> my pulse portal is 26.0.0-32.  Still unable to connect via homebridge.

what are the errors you are getting? works fine for me. are you able to access portal.adtpulse.com? if not, pause the plugin for a day, and try again.

**Comment by mdombrowski13** [comment]
I was getting
[7/28/2023, 12:11:33 PM] Homebridge v1.6.0 (HAP v0.11.0) (ADT-Homebridge) is running on port 51827.
ADT Pulse: Logging in...
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.

Resolved:
- updated to new plugin
- paused plugin for 24 hours
- logged back into web portal via chrome and updated Fingerprint
- reenabled plug in
- restarted homebrige instance 
- plugin responding again

Issue Resolved.

**Comment by mrjackyliang** [comment]
> I was getting
> 
> [7/28/2023, 12:11:33 PM] Homebridge v1.6.0 (HAP v0.11.0) (ADT-Homebridge) is running on port 51827.
> 
> ADT Pulse: Logging in...
> 
> ADT Pulse: Response path -> undefined
> 
> ADT Pulse: Response path matches -> false
> 
> ADT Pulse: Login failed.
> 
> 
> 
> Resolved:
> 
> - updated to new plugin
> 
> - paused plugin for 24 hours
> 
> - logged back into web portal via chrome and updated Fingerprint
> 
> - reenabled plug in
> 
> - restarted homebrige instance 
> 
> - plugin responding again
> 
> 
> 
> Issue Resolved.  

Awesomeness! Seems like the toggle is coming in handy!

**Comment by mdombrowski13** [comment]
Yes the toggle is very helpful!  Thank you!  I just submitted a feature request to toggle automatically after x failed login attempts and notify the user so a lockout could be prevented.
