### ISSUE TITLE
pyadtpulse has a simple page for grabbing the browser fingerprint

### ISSUE THREAD

**Issue by Danimal4326** [mrjackyliang/homebridge-adt-pulse#111]
### Is your feature request related to a problem? Please describe.
https://github.com/rsnodgrass/pyadtpulse has a page that displays the browser fingerprint.  This makes the plugin more accessible and doesn't require using developer tools in a browser

### Describe the solution you'd like:
Copy or link to instructions from their Readme:
 - After logging in, visit https://rawcdn.githack.com/rlippmann/pyadtpulse/b3a0e7097e22446623d170f0a971726fbedb6a2d/doc/browser_fingerprint.html to get your fingerprint

**Comment by mrjackyliang** [comment]
Will play with that a bit and add it into the repo!

**Comment by mrjackyliang** [comment]
Merging into #98
