### ISSUE TITLE
ADT Control

### ISSUE THREAD

**Issue by tavasjn** [mrjackyliang/homebridge-adt-pulse#114]
With the discontinuation of ADT Pulse and the move to ADT Control do you have plans of making a connection to support ADT Control?

**Comment by knedd** [comment]
You can already connect to ADT Control using the Alarm.com plugin. KevinSent via iPhoneOn Sep 22, 2023, at 07:10, tavasjn ***@***.***> wrote:﻿
With the discontinuation of ADT Pulse and the move to ADT Control do you have plans of making a connection to support ADT Control?

**Comment by tavasjn** [comment]
> You can already connect to ADT Control using the Alarm.com plugin. KevinSent via iPhoneOn Sep 22, 2023, at 07:10, tavasjn ***@***.***> wrote:﻿ With the discontinuation of ADT Pulse and the move to ADT Control do you have plans of making a connection to support ADT Control? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Sorry I may be a little confused because I can’t seem to find how to link alarm.com to ADT Control. ADT Control doesn’t show up in the list of systems on the website

**Comment by mrjackyliang** [comment]
> > You can already connect to ADT Control using the Alarm.com plugin. KevinSent via iPhoneOn Sep 22, 2023, at 07:10, tavasjn ***@***.***> wrote:﻿ With the discontinuation of ADT Pulse and the move to ADT Control do you have plans of making a connection to support ADT Control? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> 
> 
> 
> Sorry I may be a little confused because I can’t seem to find how to link alarm.com to ADT Control. ADT Control doesn’t show up in the list of systems on the website 

I believe your ADT Control login is essentially an Alarm.com login. ADT Pulse is being discontinued for new customers. As far as I know, I wasn't being forced out of ADT Pulse yet.
