### ISSUE TITLE
Accessories not responding after token refresh/upgrade

### ISSUE THREAD

**Issue by 7AC** [mrjackyliang/homebridge-adt-pulse#115]
### Describe the bug:
I've been away for a while so when I came back I realized the token had expired, and the plugin needed updating from 2.1.7 to 2.2.0. After I did all that the accessories all show as "no response" in the Home app. Looking at the logs things seems to be operating fine: it sees all the accessories and I see a bunch of these in the log for as long as it's up.

With verbose level:

```
ADT Pulse: Response path -> /myhome/26.0.0-32/Ajax/SyncCheckServ?t=1695605759391
ADT Pulse: Response path matches -> true
ADT Pulse: Portal sync success.
ADT Pulse: Performing portal sync...
ADT Pulse: Response path -> /myhome/26.0.0-32/Ajax/SyncCheckServ?t=1695605762394
ADT Pulse: Response path matches -> true
ADT Pulse: Portal sync success.
```

With info level:

```
[9/24/2023, 6:39:13 PM] [ADT Pulse] Configuring cached accessory... Security Panel (system-1)
[9/24/2023, 6:39:13 PM] [ADT Pulse] Configuring cached accessory... 2nd Bedroom 1st (sensor-16)
[9/24/2023, 6:39:13 PM] [ADT Pulse] Configuring cached accessory... 2nd Bedroom 2nd (sensor-17)
[9/24/2023, 6:39:13 PM] [ADT Pulse] Configuring cached accessory... 2nd Bedroom 3rd (sensor-18)
...
```

### Steps to reproduce the bug:
1. Just start home bridge and check the Home app

### Expected behavior:
All accessories used to show up as "live" in the home app

### The Apple device you are using:
- Device: MacBook Pro and iPhone 14
- OS: macOS 13.6 iOS 17.0

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[9/24/2023, 6:34:16 PM] [ADT Pulse] running on linux (arm)
[9/24/2023, 6:34:16 PM] [ADT Pulse] homebridge-adt-pulse v2.2.0
[9/24/2023, 6:34:16 PM] [ADT Pulse] node v18.15.0
[9/24/2023, 6:34:16 PM] [ADT Pulse] homebridge v1.6.1
```

### Logs related to this bug:
Nothing weird in the logs

**Comment by mrjackyliang** [comment]
Can you open your Home app on your MacBook and see if it's the same thing? And is this for all accessories or just all ADT sensors?

**Comment by mrjackyliang** [comment]
Oh wait, you're using iOS 17. Let me update and see if I get the same issue.

**Comment by mrjackyliang** [comment]
I updated, and my accessories are okay! Probably something is up with your network. My guess is it has to do with your mDNS.
