### ISSUE TITLE
Door sensor is reported OPEN in Homebridge but CLOSED in ADT Pulse App. The door is CLOSED.

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#116]
This just started today.

Inside Homebridge, one door sensor is showing as OPEN. But the door itself is closed, and the sensor on ADT Pulse app is showing as CLOSED. I've tried resetting the ADT bridge several times. I have changed settings to "remove obsolete zones" = TRUE. I have also restarted Homebridge. None of these has solved the problem. Weird.

**Comment by mrjackyliang** [comment]
Yes, it happened for me last night. I will be working on a remake of the entire plugin soon, as of now, I believe the plugin would be unstable.

**Comment by mrjackyliang** [comment]
My logs are constantly spammer with removeObsoleteZone logs as well

**Comment by sptv1** [comment]
Further examination - now the BASEMENT DOOR (which is the one causing problems) is no longer a problem. However, now my KITCHEN DOOR is showing up twice in the accessories panel, with two different sensor numbers. When I unblock "remove obsolete zones" most of the sensors no longer show up in Homebridge (or HomeKit). I am also getting an "unknown error occurred" in my logs, regardless of whether "obsolete zones" is true or false.

**Comment by mrjackyliang** [comment]
This is because of the website constantly changing available sensors. From my side, I would see random sensors being taken offline and online.

**Comment by mrjackyliang** [comment]
This issue will be worked on soon. Follow #98
