### ISSUE TITLE
"Exclude" Option to hide/disable sensors

### ISSUE THREAD

**Issue by grizleeeee** [mrjackyliang/homebridge-adt-pulse#118]
### Is your feature request related to a problem? Please describe.
With the recent changes to the ADT Pulse API and it breaking sensor reporting, but (at least for me) leaving Alarm Panel functionality intact, I hate having to pause the plugin just to avoid crashing homebridge/slowing it down. I'd love to maintain the Alarm Panel functionality.

### Describe the solution you'd like:
Similar to the override functionality, an exclude option to hide/disable polling of specific sensors would be really helpful.

### Describe alternatives you've considered:
I've thought about changing the sensor types or just leaving the type blank, but I had a feeling that wouldn't work as there wasn't a predefined option in the documentation.

**Comment by mrjackyliang** [comment]
I am working on a new version of the plugin right now, and today I did some API optimizations.

Will continue to code the Homebridge side of the plugin with some new scripts for quick start. Please follow issue #98 for more info!

**Comment by mrjackyliang** [comment]
The new beta version allows you to choose what sensors you want inside instead of the other way around.
