### ISSUE TITLE
Possible Display Issue: Turning on Alarm will cause Home app status to flicker

### ISSUE THREAD

**Issue by gavinpquinn-home** [mrjackyliang/homebridge-adt-pulse#125]
### Describe the bug:
When I use Home App to enable alarm "Activated - Home", it turns on the alarm, but then it turns back off after 5-10 seconds. 

### Steps to reproduce the bug:
1. In Home App, Set Alarm Active - Home.

### Expected behavior:
I would expect alarm should set to Active - Home, then stay on.

### The Apple device you are using:
This was from Sonoma 14.2 on Mac

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

[12/20/2023, 4:12:57 PM] [ADT Pulse] running on linux (arm) // homebridge-adt-pulse vunknown // homebridge v1.7.0 // node v18.18.2 // openssl v3.0.10+quic
[12/20/2023, 4:12:57 PM] [ADT Pulse] The API gathers anonymous analytics to detect potential bugs or issues. All personally identifiable information redacted. You will see exactly what will be sent out.
Setup Payload:
X-HM://xxxx
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxxxxx │     
    └────────────┘     
                       
[12/20/2023, 4:12:57 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge B227) is running on port 51936.

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
Does the system eventually arm itself?

**Comment by gavinpquinn-home** [comment]
When I set to alarm - home and waited a bit longer, this is what I noticed:- the alarm does set within 1 second- 2 seconds later it goes back to unarmed.- 3 seconds later it goes back to armed- waited 3 minutes and still armedSo yes, I guess it does then remain on.Continuing:- status in home app switches back and forth between armed and unarmed in later minutes but alarm does not change. - when I catch the app at armed - home, if I switch to “off” it does turn the alarm off. - it stayed off now.On Dec 22, 2023, at 17:08, Jacky Liang ***@***.***> wrote:﻿
Does the system eventually arm itself?

**Comment by mrjackyliang** [comment]
And are you setting from a Disarmed state? FYI, clear alarm is not disarmed state.

**Comment by gavinpquinn-home** [comment]
Yes, moving from “Off” to “Home”On Dec 23, 2023, at 10:14, Jacky Liang ***@***.***> wrote:﻿
And are you setting from a Disarmed state? FYI, clear alarm is not disarmed state.

**Comment by mrjackyliang** [comment]
Got it, will give it a test after updating the statuses and see what's going on.

**Comment by mrjackyliang** [comment]
`v3.0.0-beta.13` should be up soon. Seeing if this fixes that issue.

**Comment by mrjackyliang** [comment]
The latest update should fix it. I have seen the flicker happen a few times on my side.

**Comment by mrjackyliang** [comment]
Related to #124
