### ISSUE TITLE
[Bug]: Plugin is unable to initialize due to an invalid platform configuration.

### ISSUE THREAD

**Issue by mikezucker** [mrjackyliang/homebridge-adt-pulse#127]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have done my research, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am using the latest version of the plugin

### Your email address

sc@panjems.org

### Tell us exactly what happened

Upgraded to the beta and getting this in the log: Plugin is unable to initialize due to an invalid platform configuration.

{
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "portal",
            "path": [
              "subdomain"
            ],
            "message": "Invalid literal value, expected 'portal'"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "portal-ca",
            "path": [
              "subdomain"
            ],
            "message": "Invalid literal value, expected 'portal-ca'"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "subdomain"
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "normal",
            "path": [
              "mode"
            ],
            "message": "Invalid literal value, expected 'normal'"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "paused",
            "path": [
              "mode"
            ],
            "message": "Invalid literal value, expected 'paused'"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "reset",
            "path": [
              "mode"
            ],
            "message": "Invalid literal value, expected 'reset'"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "mode"
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": 1,
            "path": [
              "speed"
            ],
            "message": "Invalid literal value, expected 1"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": 0.75,
            "path": [
              "speed"
            ],
            "message": "Invalid literal value, expected 0.75"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": 0.5,
            "path": [
              "speed"
            ],
            "message": "Invalid literal value, expected 0.5"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": 0.25,
            "path": [
              "speed"
            ],
            "message": "Invalid literal value, expected 0.25"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "speed"
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "sensors"
    ],
    "message": "Required"
  }

### Plugin version

v3.0.0-beta.19

### Homebridge version

v3.4.3

### Node.js® version

v18.17.1

### Log output of the `test-api` command

```Shell
Unable to locate directory
```

### More logs relevant to this bug

```Shell
Nothing else really.  Just getting this error.
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
Hi @mikezucker, the configuration has changed from `v2`. Please use the new configuration UI. If you are using HOOBS, please read the README.md file for more information on what to change.

**Comment by mikezucker** [comment]
Thanks so much and my apologies for not reading carefully!

Have a great new year!

**Comment by mrjackyliang** [comment]
If you have any other questions, feel free to open up a new issue.
