### ISSUE TITLE
Right Garage Door

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#13]
<tr>
        <td class="p_whiteBoxMiddleLeft"></td>
        <td class="p_whiteBoxMiddleCenter" align="center">

    <br><span id="status" class="p_boldNormalTextLarge">Currently Closed</span><div><br><input type="button" id="action_button" name="action_button" value="Open" alt="Open" class="p_btn p_btnLnormal" onclick="doSubmit( '/myhome/17.0.0-71/quickcontrol/serv/RunRRACommand?sat=0351cd6c-bdc5-4f52-926e-ffd9c063e69c&amp;href=rest\/adt\/ui\/client\/door\/door-63\/garageDoor&amp;value=0' )" onmouseover="javascript:btnHover(this,'L')" onmouseout="javascript:btnNormal(this,'L')" onmousedown="javascript:btnDown(this,'L')" onmouseup="javascript:btnNormal(this,'L')" data-fitlabel="shrink"><style type="text/css">#testSizeaction_button {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizeaction_button" class="p_btn p_btnLnormal">Open</div></div><div><br><br><input type="button" id="cancel_button" name="cancel_button" value="Cancel" alt="Cancel" class="p_btn p_btnLnormal" onclick="closeDialog()" onmouseover="javascript:btnHover(this,'L')" onmouseout="javascript:btnNormal(this,'L')" onmousedown="javascript:btnDown(this,'L')" onmouseup="javascript:btnNormal(this,'L')" data-fitlabel="shrink"><style type="text/css">#testSizecancel_button {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizecancel_button" class="p_btn p_btnLnormal">Cancel</div><br></div>

            
        </td>
        <td class="p_whiteBoxMiddleRight"></td>
    </tr>
![Screen Shot 2019-12-08 at 1 33 36 PM](https://user-images.githubusercontent.com/36968126/70394086-601a3680-19bf-11ea-8f13-eaec1e4b028b.png)

**Comment by mrjackyliang** [comment]
Closed. Reference to issue #8.
