### ISSUE TITLE
[Feature]: Door Sensors

### ISSUE THREAD

**Issue by mikezucker** [mrjackyliang/homebridge-adt-pulse#130]
### Pre-check confirmation

- [X] I have provided a descriptive title for my feature request
- [X] I have kept the original title prefix, __"[Feature]: "__
- [X] I understand that requests for Z-Wave related accessories will __NOT__ be considered
- [X] I have confirmed that this feature is __NOT__ already present or planned

### Your email address

Door Sensors on Dashboard as Doors

### Describe the new feature requested

Currently door sensors are in the sensors part of the Home app.  Would like to see the current status of doors on the dashboard.

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
You cannot do that in Home app apparently. Not a feature that the plugin can implement or limits you from doing so.

If you would like to see sensors and be able to customize how you interface with your home, you can install the Home+ app since it shows all your accessories in a list.
