### ISSUE TITLE
Getting the same "update configuration structure" in logs.

### ISSUE THREAD

**Issue by Fergie2020** [mrjackyliang/homebridge-adt-pulse#132]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have done my research, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am using the latest version of the plugin

### Your email address

ferguson.brian@mac.com

### Tell us exactly what happened

I thought I had my plugin all set but I am getting the same message

### Plugin version

3.1.0

### Homebridge version

1.7.0

### Node.js® version

18.19.0

### Log output of the "test-api" command

```Shell
Plugin is unable to initialize due to an invalid platform configuration.
[1/27/2024, 1:04:50 PM] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  }
]
```

### More logs relevant to this bug

```Shell
"name": "ADT Pulse",
    "subdomain": "portal",
    "username": "DELETED",
    "password": "DELETED,
    "fingerprint": "eyJmaW5nZXJwcmludCI6eyJ1YUJyb3dzZXIiOnsibmFtZSI6IlNhZmFyaSIsInZlcnNpb24iOiIxNi42LjEiLCJtYWpvciI6IjE2In0sInVhU3RyaW5nIjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE2LjYuMSBTYWZhcmkvNjA1LjEuMTUiLCJ1YURldmljZSI6eyJtb2RlbCI6bnVsbCwidHlwZSI6bnVsbCwidmVuZG9yIjpudWxsfSwidWFFbmdpbmUiOnsibmFtZSI6IldlYktpdCIsInZlcnNpb24iOiI2MDUuMS4xNSJ9LCJ1YU9TIjp7Im5hbWUiOiJNYWMgT1MiLCJ2ZXJzaW9uIjoiMTAuMTUuNyJ9LCJ1YUNQVSI6eyJhcmNoaXRlY3R1cmUiOm51bGx9LCJ1YVBsYXRmb3JtIjoiTWFjSW50ZWwiLCJsYW5ndWFnZSI6ImVuLVVTIiwiY29sb3JEZXB0aCI6MjQsInBpeGVsUmF0aW8iOjEsInNjcmVlblJlc29sdXRpb24iOiIxOTIweDEwODAiLCJhdmFpbGFibGVTY3JlZW5SZXNvbHV0aW9uIjoiMTkyMHgxMDU1IiwidGltZXpvbmUiOiJBbWVyaWNhL05ld19Zb3JrIiwidGltZXpvbmVPZmZzZXQiOjMwMCwibG9jYWxTdG9yYWdlIjp0cnVlLCJzZXNzaW9uU3RvcmFnZSI6dHJ1ZSwiaW5kZXhlZERiIjp0cnVlLCJhZGRCZWhhdmlvciI6ZmFsc2UsIm9wZW5EYXRhYmFzZSI6ZmFsc2UsImNwdUNsYXNzIjpudWxsLCJwbGF0Zm9ybSI6Ik1hY0ludGVsIiwiZG9Ob3RUcmFjayI6bnVsbCwicGx1Z2lucyI6IlBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYsUG9ydGFibGUgRG9jdW1lbnQgRm9ybWF0LmFwcGxpY2F0aW9uL3BkZjo6cGRmLFBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYiLCJjYW52YXMiOiItMTkzMTUxODY5MyIsIndlYkdsIjoiMTE4Mzc2MzkyNiIsImFkQmxvY2siOmZhbHNlLCJ1c2VyVGFtcGVyTGFuZ3VhZ2UiOmZhbHNlLCJ1c2VyVGFtcGVyU2NyZWVuUmVzb2x1dGlvbiI6ZmFsc2UsInVzZXJUYW1wZXJPUyI6ZmFsc2UsInVzZXJUYW1wZXJCcm93c2VyIjpmYWxzZSwidG91Y2hTdXBwb3J0Ijp7Im1heFRvdWNoUG9pbnRzIjowLCJ0b3VjaEV2ZW50IjpmYWxzZSwidG91Y2hTdGFydCI6ZmFsc2V9LCJjb29raWVTdXBwb3J0Ijp0cnVlLCJmb250cyI6IkFjYWRlbXkgRW5ncmF2ZWQgTEVULEFtZXJpY2FuIFR5cGV3cml0ZXIsQW1lcmljYW4gVHlwZXdyaXRlciBDb25kZW5zZWQsQW5kYWxlIE1vbm8sQXBwbGUgQ2hhbmNlcnksQXBwbGUgQ29sb3IgRW1vamksQXBwbGUgU0QgR290aGljIE5lbyxBcmlhbCxBcmlhbCBCbGFjayxBcmlhbCBIZWJyZXcsQXJpYWwgTmFycm93LEFyaWFsIFJvdW5kZWQgTVQgQm9sZCxBcmlhbCBVbmljb2RlIE1TLEFWRU5JUixBeXV0aGF5YSxCYW5nbGEgU2FuZ2FtIE1OLEJhc2tlcnZpbGxlLEJhdWhhdXMgOTMsQmlnIENhc2xvbixCb2RvbmkgNzIsQm9kb25pIDcyIE9sZHN0eWxlLEJvZG9uaSA3MiBTbWFsbGNhcHMsQm9va3NoZWxmIFN5bWJvbCA3LEJyYWRsZXkgSGFuZCxCcnVzaCBTY3JpcHQgTVQsQ2hhbGtib2FyZCxDaGFsa2JvYXJkIFNFLENoYWxrZHVzdGVyLENvY2hpbixDb21pYyBTYW5zIE1TLENvcHBlcnBsYXRlLENvdXJpZXIsQ291cmllciBOZXcsRGV2YW5hZ2FyaSBTYW5nYW0gTU4sRGlkb3QsRW5nbGlzaCAxMTEgVml2YWNlIEJULEV1cGhlbWlhIFVDQVMsRnV0dXJhLEdlZXphIFBybyxHZW5ldmEsR2VvcmdpYSxHZW9TbGFiIDcwMyBMdCBCVCxHZW9TbGFiIDcwMyBYQmQgQlQsR2lsbCBTYW5zLEd1amFyYXRpIFNhbmdhbSBNTixHdXJtdWtoaSBNTixIZWl0aSBTQyxIZWl0aSBUQyxIZWx2ZXRpY2EsSGVsdmV0aWNhIE5ldWUsSGlyYWdpbm8gS2FrdSBHb3RoaWMgUHJvTixIaXJhZ2lubyBNaW5jaG8gUHJvTixIb2VmbGVyIFRleHQsSHVtYW5zdCA1MjEgQ24gQlQsSW1wYWN0LEthaWxhc2EsS2FubmFkYSBTYW5nYW0gTU4sS3J1bmd0aGVwLExVQ0lEQSBHUkFOREUsTWFsYXlhbGFtIFNhbmdhbSBNTixNYXJpb24sTWFya2VyIEZlbHQsTWljcm9zb2Z0IEpoZW5nSGVpLE1pY3Jvc29mdCBTYW5zIFNlcmlmLE1vZGVybiBOby4gMjAsTW9uYWNvLE5hZGVlbSxOb3Rld29ydGh5LE9QVElNQSxPcml5YSBTYW5nYW0gTU4sUGFsYXRpbm8sUGFweXJ1cyxQYXJ0eSBMRVQsUGxhbnRhZ2VuZXQgQ2hlcm9rZWUsUm9ja3dlbGwsUm9tYW4sU2F2b3llIExFVCxTaW1TdW4sU2luaGFsYSBTYW5nYW0gTU4sU2tpYSxTbmVsbCBSb3VuZGhhbmQsVGFob21hLFRhbWlsIFNhbmdhbSBNTixUZWx1Z3UgU2FuZ2FtIE1OLFRob25idXJpLFRpbWVzLFRpbWVzIE5ldyBSb21hbixUcmVidWNoZXQgTVMsVW5pdmVycyBDRSA1NSBNZWRpdW0sVmVyZGFuYSxXaW5nZGluZ3MsV2luZ2RpbmdzIDIsV2luZ2RpbmdzIDMsWmFwZmlubyJ9fQ==",
    "mode": "normal",
    "speed": 1,
    "sensors": [
        {
            "name": "Front Door",
            "adtName": "Front Door",
            "adtType": "doorWindow",
            "adtZone": 1
        },
        {
            "name": "Garage Door",
            "adtName": "Garage Door",
            "adtType": "doorWindow",
            "adtZone": 3
        },
        {
            "name": "Garage Glass Break Detector",
            "adtName": "Garage Glass Break Detector",
            "adtType": "glass",
            "adtZone": 5
        },
        {
            "name": "Kitchen Glass Detector",
            "adtName": "Kitchen Glass Detector",
            "adtType": "glass",
            "adtZone": 4
        },
        {
            "name": "Living Room Motion Detector",
            "adtName": "Living Room Motion Detector",
            "adtType": "motion",
            "adtZone": 6
        },
        {
            "name": "Sliding Door",
            "adtName": "Sliding Door",
            "adtType": "doorWindow",
            "adtZone": 2
        }
    ],
    "platform": "ADTPulse"
}
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
The configuration has been upgraded to accommodate some users having issues. Simply add `"options": [],` below the `"speed": 1,` line, and you should be all set.

**Comment by Fergie2020** [comment]
Got it!!! 

Thank you so much!

**Comment by mrjackyliang** [comment]
No problem!

**Comment by mrjackyliang** [comment]
![image](https://github.com/mrjackyliang/homebridge-adt-pulse/assets/9779803/265c4706-604e-4321-bb84-11e42d4c65b7)

**Comment by elight** [comment]
Odd. After adding the `options` attributes, I still get:

```
02/02/2024
02:19:06 PM
[2/2/2024, 7:19:06 PM] [ADT Pulse] Initializing ADTPulse platform...
02/02/2024
02:19:06 PM
[2/2/2024, 7:19:06 PM] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
02/02/2024
02:19:06 PM
[2/2/2024, 7:19:06 PM] [ADT Pulse] If you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
02/02/2024
02:19:06 PM
[
02/02/2024
02:19:06 PM
  {
02/02/2024
02:19:06 PM
    "code": "invalid_type",
02/02/2024
02:19:06 PM
    "expected": "array",
02/02/2024
02:19:06 PM
    "received": "undefined",
02/02/2024
02:19:06 PM
    "path": [
02/02/2024
02:19:06 PM
      "sensors"
02/02/2024
02:19:06 PM
    ],
02/02/2024
02:19:06 PM
    "message": "Required"
02/02/2024
02:19:06 PM
  }
02/02/2024
02:19:06 PM
]
```

**Comment by mrjackyliang** [comment]
> And make sure that you at least have a `"sensors": []` attribute?

Yes. If you don't want sensors, you have to set it to an empty array.

**Comment by elight** [comment]
Grateful for such timely responses!

Now I'm seeing:

```
[ADT Pulse] Login attempt has failed. Trying 1 more time ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/27.0.0-140/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
```

I know that I have the correct credentials.

**Comment by elight** [comment]
Oh perhaps my fingerprint is wrong?

**Comment by mrjackyliang** [comment]
> Oh perhaps my fingerprint is wrong?

Most likely the fingerprint became outdated or per @rlippmann's discovery, you cannot have two of the same fingerprints login at the same time.

**Comment by mrjackyliang** [comment]
If it fails 3 times in a row, the plugin will just stop for 30 mins to prevent ADT from blocking your IP due to many attempts.

**Comment by elight** [comment]
I'm getting "fingerprint `too_big`". :confused:

**Comment by mrjackyliang** [comment]
> I'm getting "fingerprint `too_big`". 😕

Mmm. this sounds like a bug. Please create a bug report, thanks!

**Comment by Fergie2020** [comment]
Just an FYI.....I woke up this morning and the plugin wouldn't work again.  Checked logs and my json file changed.  The "platform": ......  line (second from top) was gone.  Had to re-enter the the line and save/restart homebridge to get it back up and running.

**Comment by mrjackyliang** [comment]
> Just an FYI.....I woke up this morning and the plugin wouldn't work again.  Checked logs and my json file changed.  The "platform": ......  line (second from top) was gone.  Had to re-enter the the line and save/restart homebridge to get it back up and running.  

The plugin doesn't touch the platform key in the config. That's all Homebridge. If it's missing, something wanky going on with the install.

**Comment by Fergie2020** [comment]
Thanks for the update. Not sure what happened through the night but will keep you posted if anything changes. On Feb 2, 2024, at 3:36 PM, Jacky Liang ***@***.***> wrote:﻿

Just an FYI.....I woke up this morning and the plugin wouldn't work again.  Checked logs and my json file changed.  The "platform": ......  line (second from top) was gone.  Had to re-enter the the line and save/restart homebridge to get it back up and running.

The plugin doesn't touch the platform key in the config. That's all Homebridge. If it's missing, something wanky going on with the install.

**Comment by mrjackyliang** [comment]
> Thanks for the update. Not sure what happened through the night but will keep you posted if anything changes. On Feb 2, 2024, at 3:36 PM, Jacky Liang ***@***.***> wrote:﻿
> 
> 
> 
> Just an FYI.....I woke up this morning and the plugin wouldn't work again.  Checked logs and my json file changed.  The "platform": ......  line (second from top) was gone.  Had to re-enter the the line and save/restart homebridge to get it back up and running.
> 
> 
> 
> The plugin doesn't touch the platform key in the config. That's all Homebridge. If it's missing, something wanky going on with the install.
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

If you do suspect something, please file a new bug report, thanks!
