### ISSUE TITLE
[Bug]: Hoobs

### ISSUE THREAD

**Issue by tarunprakashsingh** [mrjackyliang/homebridge-adt-pulse#133]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have done my research, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am using the latest version of the plugin

### Your email address

tarunprakashsingh@gmail.com

### Tell us exactly what happened

current hoobs JSON format.
{
            "resetAll": false,
            "username": "abc@gmail.com",
            "removeObsoleteZones": true,
            "platform": "ADTPulse",
            "name": "ADT Pulse",
            "password": "xxxxxxx",
            "fingerprint": "xxxxxxxxxxxx",
            "logLevel": "10",
            "logActivity": true,
            "country": "us"
        }

what do i need to update this to? for me to get this working hoobs with latest version.

### Plugin version

3.1.1

### Homebridge version

1.7.0

### Node.js® version

16.20.2

### Log output of the "test-api" command

```Shell
current hoobs JSON format.
{
            "resetAll": false,
            "username": "abc@gmail.com",
            "removeObsoleteZones": true,
            "platform": "ADTPulse",
            "name": "ADT Pulse",
            "password": "xxxxxxx",
            "fingerprint": "xxxxxxxxxxxx",
            "logLevel": "10",
            "logActivity": true,
            "country": "us"
        }
```

### More logs relevant to this bug

```Shell
what is the new format that i can update. so i can get this working.
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
Please read the readme file. Should get you up and running again.

**Comment by tarunprakashsingh** [comment]
added this and removed old json:


 {
            "platform": "ADTPulse",
            "name": "ADT Pulse",
            "subdomain": "portal",
            "username": "abc@gmail.com",
            "password": "abc123",
            "fingerprint": "xxxxx",
            "mode": "normal",
            "speed": 1,
            "sensors": [
                null
            ]
        }
 
i am getting this error.....

1/30/2024, 12:13:27 PMHOOBSADT PulseERRORPlugin is unable to initialize due to an invalid platform configuration.
1/30/2024, 12:13:27 PMHOOBSADT PulseWARNINGIf you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
1/30/2024, 12:13:27 PMHOOBSERROR[
1/30/2024, 12:13:27 PMHOOBSERROR{
1/30/2024, 12:13:27 PMHOOBSERROR"code": "invalid_type",
1/30/2024, 12:13:27 PMHOOBSERROR"expected": "array",
1/30/2024, 12:13:27 PMHOOBSERROR"received": "undefined",
1/30/2024, 12:13:27 PMHOOBSERROR"path": [
1/30/2024, 12:13:27 PMHOOBSERROR"options"
1/30/2024, 12:13:27 PMHOOBSERROR],
1/30/2024, 12:13:27 PMHOOBSERROR"message": "Required"
1/30/2024, 12:13:27 PMHOOBSERROR},
1/30/2024, 12:13:27 PMHOOBSERROR{
1/30/2024, 12:13:27 PMHOOBSERROR"code": "invalid_type",
1/30/2024, 12:13:27 PMHOOBSERROR"expected": "object",
1/30/2024, 12:13:27 PMHOOBSERROR"received": "undefined",
1/30/2024, 12:13:27 PMHOOBSERROR"path": [
1/30/2024, 12:13:27 PMHOOBSERROR"sensors",
1/30/2024, 12:13:27 PMHOOBSERROR0
1/30/2024, 12:13:27 PMHOOBSERROR],
1/30/2024, 12:13:27 PMHOOBSERROR"message": "Required"
1/30/2024, 12:13:27 PMHOOBSERROR}
1/30/2024, 12:13:27 PMHOOBSERROR]
1/30/2024, 12:13:27 PMHOOBSADT PulseConfiguring cached accessory for undefined (id: system-1, uuid: undefined) ...
1/30/2024, 12:13:27 PMHOOBSADT PulseConfiguring cached accessory for undefined (id: sensor-0, uuid: undefined) ...
