### ISSUE TITLE
[Support]: Format Json not working on V3.1.1

### ISSUE THREAD

**Issue by tarunprakashsingh** [mrjackyliang/homebridge-adt-pulse#135]
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

{
            "platform": "ADTPulse",
            "name": "ADT Pulse",
            "subdomain": "portal",
            "username": "tarunprakashsingh@gmail.com",
            "password": "avags11",
            "fingerprint": "xxxx",
            "mode": "normal",
            "speed": 1,
            "sensors": [
                {
                    "name": "KITCHEN MOTION",
                    "adtName": "KITCHEN MOTION",
                    "adtType": "motion",
                    "adtZone": 14
                }
            ]
        }

### Logs relevant to this request

```Shell
/30/2024, 2:20:51 PMHOOBSADT PulseERRORPlugin is unable to initialize due to an invalid platform configuration.
1/30/2024, 2:20:51 PMHOOBSADT PulseWARNINGIf you just upgraded from v2 to v3 / v3.1, please update your configuration structure.
1/30/2024, 2:20:51 PMHOOBSERROR[
1/30/2024, 2:20:51 PMHOOBSERROR{
1/30/2024, 2:20:51 PMHOOBSERROR"code": "invalid_type",
1/30/2024, 2:20:51 PMHOOBSERROR"expected": "array",
1/30/2024, 2:20:51 PMHOOBSERROR"received": "undefined",
1/30/2024, 2:20:51 PMHOOBSERROR"path": [
1/30/2024, 2:20:51 PMHOOBSERROR"options"
1/30/2024, 2:20:51 PMHOOBSERROR],
1/30/2024, 2:20:51 PMHOOBSERROR"message": "Required"
1/30/2024, 2:20:51 PMHOOBSERROR}
1/30/2024, 2:20:51 PMHOOBSERROR]
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
Hello. It doesn't seem like you are a sponsor. If you would like tailored support, please consider checking out this link:

https://github.com/sponsors/mrjackyliang
