### ISSUE TITLE
[Bug]: Fingerprint "too_big"

### ISSUE THREAD

**Issue by elight** [mrjackyliang/homebridge-adt-pulse#137]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am currently having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have read the `README.md` file, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am not requesting help that is related to a support request
- [X] I am using the latest version of the plugin

### Your email address

sleight42@gmail.com

### Tell me exactly what happened

Upgrading to 3.1.1, followed the instructions in the README.

1. Logged into the ADT Pulse portal
2. Visited `https://raw.githack.com/mrjackyliang/homebridge-adt-pulse/main/fingerprint/index.html` to capture my fingerprint
3. Pasted the result into the `fingerprint` attribute in the JSON config.

Received the following JSON response:

```
{
    "code": "too_big",
    "maximum": 5120,
    "type": "string",
    "inclusive": true,
    "exact": false,
    "message": "String must contain at most 5120 character(s)",
    "path": [
      "fingerprint"
    ]
}
```

We are running a 9 y/o Pulse system here with an antiquated panel. Wondering if that is a factor?

![](https://zionssecurity.com/wp-content/uploads/2015/08/p-11930-TSSC-keypad2.png)

### Plugin version

3.1.1

### Homebridge version

1.7.0

### Node.js® version

10.4.0

### Output of the "test-api" command

```Shell
[ADT Pulse] INFO: test-api.ts - Attempt 1: Finding the Homebridge config file in "/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 2: Finding the Homebridge config file in "/var/lib/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 3: Finding the Homebridge config file in "/home/homebridge/.homebridge/config.json" ...
[ADT Pulse] ERROR: test-api.ts - Unable to find a parsable Homebridge config file with a validated "ADTPulse" platform ...

########################################################################
#####       Test has failed! Please check the error response       #####
#####  above, attempt to resolve them, then run this tester again  #####
########################################################################
```

FWIW, I verified that the config.json is in fact at `/homebridge/config.json`

### Captured logs relevant to this report

```Shell
{
    "code": "too_big",
    "maximum": 5120,
    "type": "string",
    "inclusive": true,
    "exact": false,
    "message": "String must contain at most 5120 character(s)",
    "path": [
      "fingerprint"
    ]
}
```

### Post-check confirmation

- [X] I have filled in the form __exactly as requested__ and did not attempt to circumvent form validation

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
Hmm, this is indeed a bug. I can work on a bug fix by tonight. This is just the fingerprint being longer than I anticipated.

**Comment by elight** [comment]
Curious about the `test-api` inability to find my config.json.

**Comment by mrjackyliang** [comment]
> Curious about the `test-api` inability to find my config.json.

I'm pretty sure it's the same check that's done. I have to look back at the code.

**Comment by mrjackyliang** [comment]
Ah yes, it does the same check.

**Comment by mrjackyliang** [comment]
Pushed a new update, try it out. If it still doesn't work, paste the fingerprint here and I'll figure out what's going on.

**Comment by elight** [comment]
I'm now seeing this:
```
Login attempt has failed. Trying 1 more time ...
{
  action: 'LOGIN',
  success: false,
  info: {
    message: '"/myhome/27.0.0-140/access/signin.jsp?e=ns&partner=adt" is not the summary page'
  }
}
```

**Comment by mrjackyliang** [comment]
> I'm now seeing this:
> 
> ```
> Login attempt has failed. Trying 1 more time ...
> {
>   action: 'LOGIN',
>   success: false,
>   info: {
>     message: '"/myhome/27.0.0-140/access/signin.jsp?e=ns&partner=adt" is not the summary page'
>   }
> }
> ```

Then your fingerprint is wrong. Might want to redo the fingerprint once more.

**Comment by elight** [comment]
I logged out and logged back in again several times. The fingerprint is unchanged. How can it be wrong?

**Comment by elight** [comment]
Tried from my iPad's Safari instead of Firefox on Windows.  Got a new fingerprint. Ensured I copied it correctly into the "fingerprint" attribute. Still receive that message.

**Comment by elight** [comment]
Fingerprint is
```
eyJmaW5nZXJwcmludCI6eyJ1YUJyb3dzZXIiOnsibmFtZSI6IlNhZmFyaSIsInZlcnNpb24iOiIxNy4xLjIiLCJtYWpvciI6IjE3In0sInVhU3RyaW5nIjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE3LjEuMiBTYWZhcmkvNjA1LjEuMTUiLCJ1YURldmljZSI6eyJtb2RlbCI6bnVsbCwidHlwZSI6bnVsbCwidmVuZG9yIjpudWxsfSwidWFFbmdpbmUiOnsibmFtZSI6IldlYktpdCIsInZlcnNpb24iOiI2MDUuMS4xNSJ9LCJ1YU9TIjp7Im5hbWUiOiJNYWMgT1MiLCJ2ZXJzaW9uIjoiMTAuMTUuNyJ9LCJ1YUNQVSI6eyJhcmNoaXRlY3R1cmUiOm51bGx9LCJ1YVBsYXRmb3JtIjoiTWFjSW50ZWwiLCJsYW5ndWFnZSI6ImVuLVVTIiwiY29sb3JEZXB0aCI6MjQsInBpeGVsUmF0aW8iOjIsInNjcmVlblJlc29sdXRpb24iOiIxMzY2eDEwMjQiLCJhdmFpbGFibGVTY3JlZW5SZXNvbHV0aW9uIjoiMTM2NngxMDI0IiwidGltZXpvbmUiOiJBbWVyaWNhL05ld19Zb3JrIiwidGltZXpvbmVPZmZzZXQiOjMwMCwibG9jYWxTdG9yYWdlIjp0cnVlLCJzZXNzaW9uU3RvcmFnZSI6dHJ1ZSwiaW5kZXhlZERiIjp0cnVlLCJhZGRCZWhhdmlvciI6ZmFsc2UsIm9wZW5EYXRhYmFzZSI6ZmFsc2UsImNwdUNsYXNzIjpudWxsLCJwbGF0Zm9ybSI6Ik1hY0ludGVsIiwiZG9Ob3RUcmFjayI6bnVsbCwicGx1Z2lucyI6IlBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYsUG9ydGFibGUgRG9jdW1lbnQgRm9ybWF0LmFwcGxpY2F0aW9uL3BkZjo6cGRmLFBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYiLCJjYW52YXMiOiItMTIxMDk2NzU2NyIsIndlYkdsIjoiLTQ4Mzg2MDgxNyIsImFkQmxvY2siOmZhbHNlLCJ1c2VyVGFtcGVyTGFuZ3VhZ2UiOmZhbHNlLCJ1c2VyVGFtcGVyU2NyZWVuUmVzb2x1dGlvbiI6ZmFsc2UsInVzZXJUYW1wZXJPUyI6dHJ1ZSwidXNlclRhbXBlckJyb3dzZXIiOmZhbHNlLCJ0b3VjaFN1cHBvcnQiOnsibWF4VG91Y2hQb2ludHMiOjUsInRvdWNoRXZlbnQiOnRydWUsInRvdWNoU3RhcnQiOnRydWV9LCJjb29raWVTdXBwb3J0Ijp0cnVlLCJmb250cyI6IkFjYWRlbXkgRW5ncmF2ZWQgTEVULEFtZXJpY2FuIFR5cGV3cml0ZXIsQXBwbGUgQ29sb3IgRW1vamksQXBwbGUgU0QgR290aGljIE5lbyxBcmlhbCxBcmlhbCBIZWJyZXcsQXJpYWwgUm91bmRlZCBNVCBCb2xkLEFWRU5JUixCYW5nbGEgU2FuZ2FtIE1OLEJhc2tlcnZpbGxlLEJhdWhhdXMgOTMsQm9kb25pIDcyLEJvZG9uaSA3MiBPbGRzdHlsZSxCb2RvbmkgNzIgU21hbGxjYXBzLEJvb2tzaGVsZiBTeW1ib2wgNyxCcmFkbGV5IEhhbmQsQ2hhbGtib2FyZCBTRSxDaGFsa2R1c3RlcixDb2NoaW4sQ29wcGVycGxhdGUsQ291cmllcixDb3VyaWVyIE5ldyxEQiBMQ0QgVGVtcCxEZXZhbmFnYXJpIFNhbmdhbSBNTixEaWRvdCxFbmdsaXNoIDExMSBWaXZhY2UgQlQsRXVwaGVtaWEgVUNBUyxGdXR1cmEsR2VlemEgUHJvLEdlb3JnaWEsR2VvU2xhYiA3MDMgTHQgQlQsR2VvU2xhYiA3MDMgWEJkIEJULEdpbGwgU2FucyxIZWl0aSBTQyxIZWl0aSBUQyxIZWx2ZXRpY2EsSGVsdmV0aWNhIE5ldWUsSGlyYWdpbm8gS2FrdSBHb3RoaWMgUHJvTixIaXJhZ2lubyBNaW5jaG8gUHJvTixIb2VmbGVyIFRleHQsSHVtYW5zdCA1MjEgQ24gQlQsSW1wYWN0LEthaWxhc2EsTWFsYXlhbGFtIFNhbmdhbSBNTixNYXJpb24sTWFya2VyIEZlbHQsTWljcm9zb2Z0IEpoZW5nSGVpLE1vZGVybiBOby4gMjAsTm90ZXdvcnRoeSxPUFRJTUEsUGFsYXRpbm8sUGFweXJ1cyxQYXJ0eSBMRVQsUm9ja3dlbGwsU2F2b3llIExFVCxTaW5oYWxhIFNhbmdhbSBNTixTbmVsbCBSb3VuZGhhbmQsVGFtaWwgU2FuZ2FtIE1OLFRlbHVndSBTYW5nYW0gTU4sVGhvbmJ1cmksVGltZXMsVGltZXMgTmV3IFJvbWFuLFRyZWJ1Y2hldCBNUyxVbml2ZXJzIENFIDU1IE1lZGl1bSxWZXJkYW5hLFdpbmdkaW5ncyAyLFdpbmdkaW5ncyAzLFphcGZpbm8ifX0==
```

**Comment by elight** [comment]
🤦 The password was an old password from 1Password. It's working now. Thank you!

**Comment by mrjackyliang** [comment]
Glad you got it working!

**Comment by ibogost** [comment]
```
[ADT Pulse] INFO: test-api.ts - Attempt 1: Finding the Homebridge config file in "/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 2: Finding the Homebridge config file in "/var/lib/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 3: Finding the Homebridge config file in "/home/homebridge/.homebridge/config.json" ...
[ADT Pulse] ERROR: test-api.ts - Unable to find a parsable Homebridge config file with a validated "ADTPulse" platform ...

########################################################################
#####       Test has failed! Please check the error response       #####
#####  above, attempt to resolve them, then run this tester again  #####
########################################################################
```

I am also seeing this error when trying to test. The above comments did not make it clear if a potential issue with a fingerprint was confirmed or not. The fingerprint in question is:

> eyJmaW5nZXJwcmludCI6eyJ1YUJyb3dzZXIiOnsibmFtZSI6IkNocm9tZSIsInZlcnNpb24iOiIxMjEuMC4wLjAiLCJtYWpvciI6IjEyMSJ9LCJ1YVN0cmluZyI6Ik1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjEuMC4wLjAgU2FmYXJpLzUzNy4zNiIsInVhRGV2aWNlIjp7Im1vZGVsIjpudWxsLCJ0eXBlIjpudWxsLCJ2ZW5kb3IiOm51bGx9LCJ1YUVuZ2luZSI6eyJuYW1lIjoiV2ViS2l0IiwidmVyc2lvbiI6IjUzNy4zNiJ9LCJ1YU9TIjp7Im5hbWUiOiJNYWMgT1MiLCJ2ZXJzaW9uIjoiMTAuMTUuNyJ9LCJ1YUNQVSI6eyJhcmNoaXRlY3R1cmUiOm51bGx9LCJ1YVBsYXRmb3JtIjoiTWFjSW50ZWwiLCJsYW5ndWFnZSI6ImVuLVVTIiwiY29sb3JEZXB0aCI6MjQsInBpeGVsUmF0aW8iOjIsInNjcmVlblJlc29sdXRpb24iOiIyODgweDE2MjAiLCJhdmFpbGFibGVTY3JlZW5SZXNvbHV0aW9uIjoiMjg4MHgxNTI2IiwidGltZXpvbmUiOiJBbWVyaWNhL0NoaWNhZ28iLCJ0aW1lem9uZU9mZnNldCI6MzYwLCJsb2NhbFN0b3JhZ2UiOnRydWUsInNlc3Npb25TdG9yYWdlIjp0cnVlLCJpbmRleGVkRGIiOnRydWUsImFkZEJlaGF2aW9yIjpmYWxzZSwib3BlbkRhdGFiYXNlIjpmYWxzZSwiY3B1Q2xhc3MiOm51bGwsInBsYXRmb3JtIjoiTWFjSW50ZWwiLCJkb05vdFRyYWNrIjpudWxsLCJwbHVnaW5zIjoiUG9ydGFibGUgRG9jdW1lbnQgRm9ybWF0LmFwcGxpY2F0aW9uL3BkZjo6cGRmLFBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYsUG9ydGFibGUgRG9jdW1lbnQgRm9ybWF0LmFwcGxpY2F0aW9uL3BkZjo6cGRmLFBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZiIsImNhbnZhcyI6Ii03NDcyODc2NjQiLCJ3ZWJHbCI6IjQ3OTAzNTI1OCIsImFkQmxvY2siOmZhbHNlLCJ1c2VyVGFtcGVyTGFuZ3VhZ2UiOmZhbHNlLCJ1c2VyVGFtcGVyU2NyZWVuUmVzb2x1dGlvbiI6ZmFsc2UsInVzZXJUYW1wZXJPUyI6ZmFsc2UsInVzZXJUYW1wZXJCcm93c2VyIjpmYWxzZSwidG91Y2hTdXBwb3J0Ijp7Im1heFRvdWNoUG9pbnRzIjowLCJ0b3VjaEV2ZW50IjpmYWxzZSwidG91Y2hTdGFydCI6ZmFsc2V9LCJjb29raWVTdXBwb3J0Ijp0cnVlLCJmb250cyI6IkFjYWRlbXkgRW5ncmF2ZWQgTEVULEFtZXJpY2FuIFR5cGV3cml0ZXIsQW5kYWxlIE1vbm8sQXBwbGUgQ2hhbmNlcnksQXBwbGUgQ29sb3IgRW1vamksQXBwbGUgU0QgR290aGljIE5lbyxBcmlhbCxBcmlhbCBCbGFjayxBcmlhbCBIZWJyZXcsQXJpYWwgTmFycm93LEFyaWFsIFJvdW5kZWQgTVQgQm9sZCxBcmlhbCBVbmljb2RlIE1TLEFWRU5JUixBeXV0aGF5YSxCYW5nbGEgU2FuZ2FtIE1OLEJhc2tlcnZpbGxlLEJhdWhhdXMgOTMsQmlnIENhc2xvbixCb2RvbmkgNzIsQm9kb25pIDcyIE9sZHN0eWxlLEJvZG9uaSA3MiBTbWFsbGNhcHMsQm9va3NoZWxmIFN5bWJvbCA3LEJyYWRsZXkgSGFuZCxCcnVzaCBTY3JpcHQgTVQsQ2hhbGtib2FyZCxDaGFsa2JvYXJkIFNFLENoYWxrZHVzdGVyLENvY2hpbixDb21pYyBTYW5zIE1TLENvcHBlcnBsYXRlLENvdXJpZXIsQ291cmllciBOZXcsRGV2YW5hZ2FyaSBTYW5nYW0gTU4sRGlkb3QsRW5nbGlzaCAxMTEgVml2YWNlIEJULEV1cGhlbWlhIFVDQVMsRnV0dXJhLEdlZXphIFBybyxHZW5ldmEsR2VvcmdpYSxHZW9TbGFiIDcwMyBMdCBCVCxHZW9TbGFiIDcwMyBYQmQgQlQsR2lsbCBTYW5zLEd1amFyYXRpIFNhbmdhbSBNTixHdXJtdWtoaSBNTixIZWl0aSBTQyxIZWl0aSBUQyxIZWx2ZXRpY2EsSGVsdmV0aWNhIE5ldWUsSGlyYWdpbm8gS2FrdSBHb3RoaWMgUHJvTixIaXJhZ2lubyBNaW5jaG8gUHJvTixIb2VmbGVyIFRleHQsSHVtYW5zdCA1MjEgQ24gQlQsSW1wYWN0LEthaWxhc2EsS2FubmFkYSBTYW5nYW0gTU4sS3J1bmd0aGVwLExVQ0lEQSBHUkFOREUsTWFsYXlhbGFtIFNhbmdhbSBNTixNYXJpb24sTWFya2VyIEZlbHQsTWljcm9zb2Z0IFNhbnMgU2VyaWYsTW9kZXJuIE5vLiAyMCxNb25hY28sTmFkZWVtLE5vdGV3b3J0aHksT1BUSU1BLE9yaXlhIFNhbmdhbSBNTixQYWxhdGlubyxQYXB5cnVzLFBhcnR5IExFVCxQbGFudGFnZW5ldCBDaGVyb2tlZSxSb2Nrd2VsbCxTYXZveWUgTEVULFNpbmhhbGEgU2FuZ2FtIE1OLFNraWEsU25lbGwgUm91bmRoYW5kLFRhaG9tYSxUYW1pbCBTYW5nYW0gTU4sVGVsdWd1IFNhbmdhbSBNTixUaG9uYnVyaSxUaW1lcyxUaW1lcyBOZXcgUm9tYW4sVHJlYnVjaGV0IE1TLFVuaXZlcnMgQ0UgNTUgTWVkaXVtLFZlcmRhbmEsV2luZ2RpbmdzLFdpbmdkaW5ncyAyLFdpbmdkaW5ncyAzLFphcGZpbm8ifX0

**Comment by mrjackyliang** [comment]
> ```
> [ADT Pulse] INFO: test-api.ts - Attempt 1: Finding the Homebridge config file in "/homebridge/config.json" ...
> [ADT Pulse] INFO: test-api.ts - Attempt 2: Finding the Homebridge config file in "/var/lib/homebridge/config.json" ...
> [ADT Pulse] INFO: test-api.ts - Attempt 3: Finding the Homebridge config file in "/home/homebridge/.homebridge/config.json" ...
> [ADT Pulse] ERROR: test-api.ts - Unable to find a parsable Homebridge config file with a validated "ADTPulse" platform ...
> 
> ########################################################################
> #####       Test has failed! Please check the error response       #####
> #####  above, attempt to resolve them, then run this tester again  #####
> ########################################################################
> ```
> 
> I am also seeing this error when trying to test. The above comments did not make it clear if a potential issue with a fingerprint was confirmed or not, or if any other problem might cause this.

@ibogost Let me see if I can print out the zod errors.

**Comment by ibogost** [comment]
Will do, thx.
