### ISSUE TITLE
[Bug]: Error loading the plug in

### ISSUE THREAD

**Issue by itessler** [mrjackyliang/homebridge-adt-pulse#140]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am currently having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have read the `README.md` file, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am not requesting help that is related to a support request
- [X] I am using the latest version of the plugin

### Your email address

ira@tessler.net

### Tell me exactly what happened

[3/8/2024, 8:48:00 AM] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[3/8/2024, 8:48:00 AM] [ADT Pulse] If you just upgraded from "v2 to v3" or from "v3 to v3.1", please update your configuration.
[3/8/2024, 8:48:00 AM] [ADT Pulse] Carefully observe the error below. The answer you are looking for is there.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "sensors"
    ],
    "message": "Required"
  }

### Plugin version

3.2.9

### Homebridge version

1.7.0

### Node.js® version

18.19.0

### Output of the "test-api" command

```Shell
[ADT Pulse] INFO: test-api.ts - Attempt 1: Finding the Homebridge config file in "/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 2: Finding the Homebridge config file in "/var/lib/homebridge/config.json" ...
[ADT Pulse] INFO: test-api.ts - Attempt 3: Finding the Homebridge config file in "/home/ira/.homebridge/config.json" ...
[ADT Pulse] ERROR: test-api.ts - Unable to find a parsable Homebridge config file with a validated "ADTPulse" platform ...
[ADT Pulse] WARNING: test-api.ts - If you just upgraded from "v2 to v3" or from "v3 to v3.1", please update your configuration ...
[ADT Pulse] WARNING: test-api.ts - Carefully observe the error below. The answer you are looking for is there ...
{
  "success": false,
  "error": {
    "issues": [
      {
        "code": "invalid_type",
        "expected": "array",
        "received": "undefined",
        "path": [
          "options"
        ],
        "message": "Required"
      },
      {
        "code": "invalid_type",
        "expected": "array",
        "received": "undefined",
        "path": [
          "sensors"
        ],
        "message": "Required"
      }
    ],
    "name": "ZodError"
  }
}

########################################################################
#####       Test has failed! Please check the error response       #####
#####  above, attempt to resolve them, then run this tester again  #####
########################################################################
npm notice 
npm notice New minor version of npm available! 10.2.3 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
```

### Captured logs relevant to this report

```Shell
[3/8/2024, 8:48:00 AM] [ADT Pulse] Plugin is unable to initialize due to an invalid platform configuration.
[3/8/2024, 8:48:00 AM] [ADT Pulse] If you just upgraded from "v2 to v3" or from "v3 to v3.1", please update your configuration.
[3/8/2024, 8:48:00 AM] [ADT Pulse] Carefully observe the error below. The answer you are looking for is there.
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "options"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "sensors"
    ],
    "message": "Required"
  }
```

### Post-check confirmation

- [X] I have filled in the form __exactly as requested__ and did not attempt to circumvent form validation

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by itessler** [comment]
Config file:

{
    "name": "ADT Pulse",
    "subdomain": "portal",
    "username": "ira@tessler.net",
    "password": "redacted",
    "fingerprint": "redacted
    "speed": 1,
    "_bridge": {
        "username": "0E:1D:ED:FC:5C:56",
        "port": 35692
    },
    "platform": "ADTPulse"
}

**Comment by mrjackyliang** [comment]
@itessler You are missing the `options` and `sensors` settings as mentioned in the error message. They must be there even if you don't have any.

**Comment by itessler** [comment]
Thank you! I got it to work.
