### ISSUE TITLE
[Support]: ADT Pulse site is down for maintenance

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#146]
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

If you are having issues logging in the ADT Pulse, it's because the site is down for maintenance.  ADT customer support could not give an ETA for restoration. 

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
ADT won't give you an answer, because the platform isn't run by them.

It's Alarm.com that does it. If they break the web portal, you would need to wait until the maintenance period is over.

**Comment by mrjackyliang** [comment]
Is the plugin working for you? If it is, I will keep this issue closed.
