### ISSUE TITLE
[Bug]: Cannot login to ADT Pulse (Invalid Fingerprint, Fingerprint Tool Bug, ADT Pulse Latest Changes)

### ISSUE THREAD

**Issue by mrfatboy** [mrjackyliang/homebridge-adt-pulse#147]
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

Still get same login errors.
![Capture](https://github.com/user-attachments/assets/bd4f54c0-0bce-4f1d-af3d-4ccff83a2cdc)

Please see closed issue here:
https://github.com/mrjackyliang/homebridge-adt-pulse/issues/144

### Logs relevant to this issue

```Shell
see above
```

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
I believe your IP is banned from the ADT Pulse portal it seems. Are you able to access the web portal directly on your browser? I'm working on the plugin right now, and I'm not having such issues.

**Comment by mrjackyliang** [comment]
Please run the `test-api` script and post your results here.

**Comment by mrfatboy** [comment]
![Capture2](https://github.com/user-attachments/assets/b35855ed-c40b-4d58-bfd1-f5ec2c0d3b84)

**Comment by mrfatboy** [comment]
More info.  Homebridge is running in Hyper V in Windows 11.  I logged into ADT Pulse and selected trust this computer on the Windows 11 side.  I then use the ADT Pulse fingerprinter Detector an copied that into the config file.

**Comment by mrjackyliang** [comment]
The logs are telling you should refresh your fingerprint. I assume you made changes to the trusted devices on your account?

**Comment by mrfatboy** [comment]
i just did all of that and I get the same error.

**Comment by mrjackyliang** [comment]
Can you tell me step by step on how you generated the fingerprint and how you logged in?

- Did you switch browsers?
- Did you use private browsing mode/Safari?

Small things like this affect the outcome of the fingerprint, because if it was the correct fingerprint that was authorized, it should not have this error.

**Comment by mrfatboy** [comment]
I used Brave browser. Shields down. 

Logged into adt pulse. Sent code to phone to authorize. Selected "trust this computer"

Opened up adt fingerprint getter in Brave. Copied fingerprint. Pasted into adt plugin config UI. 

Also doubled check of same finger print in config.json. 

Restart Homebridge. Get the error.

**Comment by mrjackyliang** [comment]
> I used Brave browser. Shields down. 
> 
> Logged into adt pulse. Sent code to phone to authorize. Selected "trust this computer"
> 
> Opened up adt fingerprint getter in Brave. Copied fingerprint. Pasted into adt plugin config UI. 
> 
> Also doubled check of same finger print in config.json. 
> 
> Restart Homebridge. Get the error. 

Can you copy the fingerprint that you have and do a base64 decode? You can send the fingerprint to my email (contact@mrjackyliang.com).

**Comment by mrfatboy** [comment]
I just sent the fingerprint and base64 decode to your email.

**Comment by mrjackyliang** [comment]
I used the fingerprint that you sent, and it logs in fine.

**Comment by mrfatboy** [comment]
I don't know what to say. Could it be something about the VM?

What else could be different?

**Comment by mrjackyliang** [comment]
Other people aren't having the same issue that you are. The other issue was a weird maintenance period issue, which also happened to me as well. That subsided already, and my login works.

However, you can try running this code on your browser while on the ADT Pulse login page, and compare the value to your fingerprint.
```
window.document.getElementById('fingerprint').value
```

**Comment by mrfatboy** [comment]
I ran the code.  The values are the same.  Regarding the other issues on https://github.com/mrjackyliang/homebridge-adt-pulse/issues/144

It seems exactly the same errors.

**Comment by mrfatboy** [comment]
more info;
The VM is running:
 Ubuntu Focal (20.04.5 LTS)
Node.js v18.13.0
ADT Pulse plugin v3.3.1

**Comment by mrjackyliang** [comment]
> I ran the code. The values are the same. Regarding the other issues on #144
> 
> It seems exactly the same errors.

The others aren't getting HTTP 500 errors, they're getting automatic signout errors. The logs look very much the same, but the story it tells is very different

**Comment by mrfatboy** [comment]
I'm at a loss.  Your plugin used to work for me before I upgraded to v3 and I switch to a windows 11 VM.

**Comment by mrfatboy** [comment]
However, i was running homebridge in windows 10 natively and not in Hyper V

**Comment by mrjackyliang** [comment]
I haven't tested this plugin in hyper-V before, but I can spend some time to see what's up there

**Comment by mrfatboy** [comment]
Maybe the fingerprint doesn't work the same in a VM?

**Comment by mrjackyliang** [comment]
> Maybe the fingerprint doesn't work the same in a VM?

It should be the same. There aren't any special requirements based on OS.

**Comment by mrfatboy** [comment]
Something is funky. Tomorrow I will setup another Homebridge instance in native Linux box and see if the plugin works there.  I will report back. 

If you come at it from a the VM side and see if the plugin is acting differently maybe we can solve it. :)

**Comment by mrjackyliang** [comment]
Will report back. Installing ubuntu 20 now.

**Comment by mrjackyliang** [comment]
I suspect ADT made some changes to the fingerprint script. The fingerprint used to log in is not the same as the one generated using the fingerprint tool.

**Comment by mrjackyliang** [comment]
Okay, I think I found out what's going on. ADT made changes to the fingerprint script so the fingerprint would generate different values when run from another website.

For now, don't use the fingerprint tool. I will be phasing it out in the next version.

Instructions on how to get up and running now:
1. Login to ADT Pulse, and delete all the trusted devices (just to get all the weird problems out of the way)
2. Use the code `window.document.getElementById('fingerprint').value` to get the fingerprint and save it in your Homebridge config. DO THIS BEFORE YOU LOGIN. DO NOT RESTART HOMEBRIDGE YET.
3. Login to your ADT Pulse account and do the usual verification and device saving.
4. Restart Homebridge.

**Comment by mrfatboy** [comment]
Great. I will do it first thing in the morning and report back 👍

**Comment by mrfatboy** [comment]
Followed your above instructions and everything looks good so far.  I'm glad we tracked down the issue. :)

**Comment by mrjackyliang** [comment]
Nice, looks like I came in just as I was about to phase out the fingerprint tool🤣 Man, this timing is amazing.

**Comment by mrjackyliang** [comment]
`v3.4.0` now automatically generates a random fingerprint for you. No more fingerprint tool required.
