### ISSUE TITLE
[Support]: No Push Notifications Not Showing In Home App or Iphone

### ISSUE THREAD

**Issue by mrfatboy** [mrjackyliang/homebridge-adt-pulse#148]
### Pre-check confirmation

- [X] I am currently sponsoring you or have heavily contributed to this project.
- [X] I have kept the original title prefix, __"[Support]: "__

### Tell me exactly what happened

I'm not getting any Push notification in the Home app or my iphone when motion, door/window sensors are triggered.  In the homebridge log, everything shows and updates correctly when sensors are triggered.

Push notifications are ON for the Home app in my Apple iphone settings as well as "allow notifications" for the ADT bridge in the Home app.

Are there still supposed to be Push notifications in V3?  They used to work in V2 of this plugin.

Suggestions?

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by mrjackyliang** [comment]
You have to individually turn them on in the Home app. It's somewhere in the app.

**Comment by mrjackyliang** [comment]
Also if you can, please do consider sponsoring for support, thanks!
