### ISSUE TITLE
Hoobs support

### ISSUE THREAD

**Issue by cjwyche95** [mrjackyliang/homebridge-adt-pulse#150]
### Pre-check confirmation

- [X] I have provided a descriptive title for the bug I am currently having
- [X] I have kept the original title prefix, __"[Bug]: "__
- [X] I have read the `README.md` file, and this is __NOT__ a duplicate bug report
- [X] I am __NOT__ requesting a new feature
- [X] I am not requesting help that is related to a support request
- [X] I am using the latest version of the plugin

### Your email address

cjwyche95@gmail.com

### Tell me exactly what happened

Hello- I have been trying to use the plugin with my Hoobs box, version 5.0.  Unfortunately, it doesn’t seem to work.  Any suggestions to get working would be appreciated.

### Plugin version

3.4.4

### Homebridge version

Hoobs 5.1.6

### Node.js® version

18.17.1

### Output of the "test-api" command

```Shell
I do not have access in Hoobs
```

### Captured logs relevant to this report

```Shell
11:17:24 AMHoobsADT PulsewarnIf you just upgraded from v2 to v3, the configuration has been changed. Please re-configure your plugin.
11:17:24 AMHoobsADT PulsewarnCarefully observe the error below. The answer you are looking for is there.
11:17:24 AMHoobsADT PulseinfoConfiguring cached accessory for undefined (id: system-1, uuid: undefined)
```

### Post-check confirmation

- [X] I have filled in the form __exactly as requested__ and did not attempt to circumvent form validation

### Legal Agreements

- [X] I agree to the Terms of Use and Privacy Policy

**Comment by cjwyche95** [comment]
Thank you.  I configured using JSON with no luck.On Nov 27, 2024, at 3:40 PM, Jacky Liang ***@***.***> wrote:﻿
HOOBS is most likely still using the old configuration meant for v2. Unless HOOBS takes action to rectify this issue, all users that use HOOBS will need to manually configure the plugin using JSON.

**Comment by mrjackyliang** [comment]
This seems to be an environment specific issue, but if you can re-do the entire configuration manually using the example in the readme, it should work.

**Comment by cjwyche95** [comment]
Okay.  Thanks.On Nov 27, 2024, at 4:10 PM, Jacky Liang ***@***.***> wrote:﻿
This seems to be an environment specific issue, but if you can re-do the entire configuration manually using the example in the readme, it should work.
