### ISSUE TITLE
Alarm Status or Sensors Not Updating on HomeKit

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#16]
**Describe the bug**
The status of the alarm is not updating correctly in the HomeKit tile for the alarm.  Despite the system being armed to "Home", "Away", or "Night", the HomeKit tile for the alarm says "Off"

**To Reproduce**
1. Go to HomeKit tile for the alarm; set to "Away", "Home" or "Night"; 
2. The alarm sets properly
3. But the status on the tile remains "Off".

**Expected behavior**
The status of the alarm tile in HomeKit should match the state of the alarm.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 High Sierra
 - Browser Safari 10.0.4

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: IOS 13.3
 - Browser Chrome
 - Version 79.0.3945.73

**Additional context**

**Comment by mrjackyliang** [comment]
What version of the plugin are you using? I remember I made a mistake in `v1.6.5` and fixed it in `v1.6.6`.

**Comment by knedd** [comment]
1.6.6

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
Are all the statuses not updating? Including the motion sensors?

**Comment by knedd** [comment]
Everything else is working fine. It’s just the state of the alarm that is not working properly. 

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
Restart Homebridge, and try arming again. I am connected to the debug logger at the moment.

**Comment by knedd** [comment]
Ok doing this now. 

Kevin

Sent via iPhone

**Comment by knedd** [comment]
After a homebridge restart it is working as it should now. Any idea what happened before?

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
I'm seeing the logs, and they look like they are performing correctly. It could possibly be a stalled Homebridge.

<img width="933" alt="Screen Shot 2019-12-27 at 2 59 54 PM" src="https://user-images.githubusercontent.com/9779803/71530768-8d208180-28b9-11ea-9356-c8929bc719d0.png">

**Comment by mrjackyliang** [comment]
The same thing happened to me the other day, but it wasn't isolated to a single plugin. All my lights were changing statuses, but it wasn't displaying correctly.

**Comment by mrjackyliang** [comment]
Hey @knedd, are you having constant syncing issues after the recent `18.0.0-78` upgrade? I noticed that I have to restart my Homebridge about two times everyday.

**Comment by knedd** [comment]
Hi Jackie,

Yes I am having the issue of having my alarm not showing the right status. I am having to restart Homebridge to correct. 

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
Yes, it took a while for me to figure out this was happening very frequently. Testing the bug fix now, and will push an update in about a day or so.

**Comment by knedd** [comment]
Happy to hear this!

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
Version `1.7.6` is out now. I've made some improvements towards the portal syncing which may fix that issue. Closing for now!
