### ISSUE TITLE
Upgrading between v1.6.7 to v1.7.0 (Users with Glass Break Sensors)

### ISSUE THREAD

**Issue by frnhgt** [mrjackyliang/homebridge-adt-pulse#17]
Without having read the release notes for 1.6.8, I updated to 1.7.0 via the HOOBS interface. This is killing Homebridge as described and I’m unsure how to proceed without a rebuild. Uninstalling this plugin and rebooting doesn’t resolve. Is there a way to go back to 1.6.7 manually to get back to a stable state?  

Thanks as always.

**Comment by mrjackyliang** [comment]
Are you having the `getCharacteristic` error in the Homebridge logs?

**Comment by frnhgt** [comment]
Yeah. I had intended to include and I suppose didn’t. I removed the config references and attempting to reinstall now , but I’m back up and running for the moment.

**Comment by mrjackyliang** [comment]
If I am correct, if you have upgraded the plugin without reading the release notes, it shouldn't have done any harm to the cached accessories.

But, let's try this sequentially:
`npm install homebridge-adt-pulse@1.6.7`
`npm install homebridge-adt-pulse@1.6.8`
`npm install homebridge-adt-pulse@1.6.9`
`npm install homebridge-adt-pulse@1.7.0`

Remember to restart on each attempt. Homebridge doesn't correctly reload the plugin after upgrading apparently.

**Comment by frnhgt** [comment]
It’s only complicated as I’m running updates from my phone as I’m away from home. I’ll step back through them manually tomorrow when hopefully I’ll be back in front of a laptop. Thanks for the quit response. And the great plugin.

**Comment by mrjackyliang** [comment]
Thanks for the support👍 and sorry about the release note headline not being more obvious. I'll keep this pinned, so to let other users (with glass break sensors) know about it.

**Comment by frnhgt** [comment]
This wouldn’t have happened if I was in lock-step with your releases as I normally am. I got behind while on vacation. Cheers!

**Comment by mrjackyliang** [comment]
Haha, I tend to be pretty quick with the updates😅

I just tested the plugin upgrade/downgrade on my side, and it works. Going to wait for confirmation before closing this issue. Let me know how it goes!

**Comment by frnhgt** [comment]
All set!

**Comment by mrjackyliang** [comment]
Cool! Closing the issue now!
