### ISSUE TITLE
ADT Pulse New Release

### ISSUE THREAD

**Issue by gdavids57** [mrjackyliang/homebridge-adt-pulse#18]
### Describe the bug:
It appears ADT have updated their Web Portal API to version 18.0.0 which is triggering a warning in the plugin.

### Steps to reproduce the bug:
Just cause an ADT action and the plugin will log the warning

### Expected behavior:
There hasn't been any warning until this new release

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

[1/27/2020, 7:59:12 AM] [ADT Pulse] running on linux (arm)
[1/27/2020, 7:59:12 AM] [ADT Pulse] homebridge-adt-pulse v1.7.3
[1/27/2020, 7:59:12 AM] [ADT Pulse] node v12.14.1
[1/27/2020, 7:59:12 AM] [ADT Pulse] homebridge v0.4.50

**Comment by mrjackyliang** [comment]
Thank you @gdavids57! Working on that soon!

**Comment by mrjackyliang** [comment]
I have added support for `18.0.0-78` and removed support for `17.0.0-69` with `v1.7.4`. Closing this issue now!
