### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by gdavids57** [mrjackyliang/homebridge-adt-pulse#19]
### Describe the solution you'd like:
An ability to see live camera feeds. 

### Describe alternatives you've considered
None, other than the ADT app or the ADT Pulse portal.

**Comment by mrjackyliang** [comment]
Hi, I mentioned in the README that I won't be supporting Z-Wave devices connected to ADT Pulse (that includes the camera).

Especially with cameras, there has not been a RTSP protocol available to stream to HomeKit. For other devices, there are Z-Wave plugins like `homebridge-zwave`.

Closing for now.

**Comment by gdavids57** [comment]
Upon further analysis, I've confirmed that my ADT Pulse environment integrates cameras via a wifi interface from the Pulse Gateway.  Does this have any impact on the plugin's ability to stream video?

**Comment by mrjackyliang** [comment]
If you are able to access the video stream via VLC, you should be able to connect it using `homebridge-camera-ffmpeg`.
