### ISSUE TITLE
Request for inclusion of additional ADT Pulse Z-Wave Devices

### ISSUE THREAD

**Issue by idallasj** [mrjackyliang/homebridge-adt-pulse#21]
### Is your feature request related to a problem? Please describe.
I am not able to see my ADT Pulse Z-WAVE Thermostats, Cameras, Appliance Module and Wall switch in Homebridge.

### Describe the solution you'd like:
I would like the support for the following devices to be added to your Homebridge ADT Pulse plugin:

- RCS TZ43A Thermostat: TZ43A (I have one of these)
- RCSRCS TZ43 Thermostat: TZ43  (I have two of these)
- RC8021W-ADT Wireless Indoor Camera (I have 3 of these)
- Fluorescent Light and Appliance Module Model: ZW4101
- GE Z-WAVE PLUS ON/OFF SMART WALL SWITCH

### Describe alternatives you've considered:
I am still looking to see if any other Homebridge plugins support these devices. I have not found one that does nor require a z-wave hub, which I do not own or plan to purchase. I plan to install only Homekit compatible devices going forward but do not wish to replace my z-wave devices which are currently working fine for my needs.

**Comment by mrjackyliang** [comment]
For the ADT Pulse Z-Wave function, I am unable to support it with the same reason that I have specified in recent issues.

__Icontrol One__ is being phased out by ADT in favor of __ADT Control__ (and that I don't have that system, so I can't develop that).

If you have found a solution that is able to connect Z-Wave devices into HomeKit, your best bet is to use that.

Developing Z-Wave solutions for a platform that is going to be phased out is not worth my time, especially when ADT may plan on moving us over.

And so for that reason, I will be closing this issue.
