### ISSUE TITLE
Add support for Web Portal version 19.0.0-89

### ISSUE THREAD

**Issue by Danimal4326** [mrjackyliang/homebridge-adt-pulse#26]
### Describe the bug:
ADT reporting I'm on Web Portal version 19.0.0-89

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
[4/28/2020, 10:01:00 PM] [ADT Pulse] Web Portal version 19.0.0-89 does not match 17.0.0-71 or 18.0.0-78.
```

**Comment by mrjackyliang** [comment]
Yep, noticed it a few days ago. Might need some time as I saw there was a potential login and stall issue.

**Comment by Danimal4326** [comment]
FYI, I modified the code to allow 19.0.0-89 and things seem to be working.  Not fully tested, but logs in and lets me arm panel, sensors seem to be updating..

**Comment by mrjackyliang** [comment]
Yeah, the check is just there to let me know some changes may be expected.

**Comment by mrjackyliang** [comment]
Version `1.8.7` is out now! Closing.
