### ISSUE TITLE
Sensor Notifications Resetting

### ISSUE THREAD

**Issue by mikezucker** [mrjackyliang/homebridge-adt-pulse#27]
### Describe the bug:
Sensor Notifications

### Steps to reproduce the bug:
1. Repeatedly enabled notifications on the home app.

### Expected behavior:
I have noticed that the when I turn notification on for sensors in the house, that after I turn them on, after a few hours they go back to being off.

### The Apple device you are using:
- Device: iPhone 10
- OS: [e.g. iOS 13.4.1

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
The issue has been fixed already. Please review issue #25.

**Comment by mikezucker** [comment]
Thanks and apologize for the repeats.
