### ISSUE TITLE
Sensors are being reverted back to "Default Room"

### ISSUE THREAD

**Issue by mikezucker** [mrjackyliang/homebridge-adt-pulse#28]
### Describe the bug:
What do you think the problem relates to?

### Steps to reproduce the bug:
1. After selecting different room, revert back to 'Default' room

### Expected behavior:
I have changed the room which multiple sensors are in multiple times.  However they always revert back to the Default room.  I expect them to stay as the room selected.

### The Apple device you are using:
- Device: iPhone 10
- OS: iOS 13.4.1

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
The issue has been fixed already. Please review issue #25.
