### ISSUE TITLE
Accessories are being Reset to Default Room

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#30]
### Describe the bug:
Using ADT Pulse on HOOBS with Homekit.

Devices all show up in the DEFULT ROOM.  I move them around the the appropriate rooms within my home set up, changing notification and favorite settings on each, but they all end up back in the Default Room with the default settings.  This happened when I updated the ADT Pulse plug in, but it also happened a number of other times at random which I cannot pinpoint or recreate.

Also, curious as to why some of my smoke detectors are showing up as contact sensors and some are showing up accurately as smoke detectors.  In the ADT Pulse app they all appear as smoke detectors.

### Steps to reproduce the bug:
1. 

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
With sensors being reset back to default, please check issue #25 for a resolution. For the issue regarding weird sensor types, please refer to issue #22.

If there are weird sensor types, please send a list of your device names to issue #22. Since this is a duplicate, I will be closing this. Chat there!
