### ISSUE TITLE
Add Light Switch, Outlet, and Door Lock

### ISSUE THREAD

**Issue by azmurph** [mrjackyliang/homebridge-adt-pulse#31]
Hi.  Thanks for all your hardwork. Any chance in adding support for the following pulse devices :
Light switch
Outlet
Doorlock

Thanks.

**Comment by knedd** [comment]
I had this discussion with Jacky a while ago. He explained the difficulty of including Pulse Smart Devices. 

I was able to include my z wave devices by adding a Smarthings hub and the homebridge SmartThings V2 plugin. 

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
It is not possible to add any devices that connect through the Z-Wave protocol at this moment. This is due to the hidden implementation of the API, and its defunct protocol. Closing.
