### ISSUE TITLE
Sensors Reset to Default Name/Room at Random Times and Wrong Sensor Types

### ISSUE THREAD

**Issue by w1llf0rd** [mrjackyliang/homebridge-adt-pulse#33]
### Describe the bug:
What do you think the problem relates to?
It might have to do with being on the new iOS beta but I am unsure. 

### Steps to reproduce the bug:
1. N/A Over the last few days the sensors have defaulted to the default room at random times so no way to reproduce the bug.

### Expected behavior:
The room and name of the sensors should stay the way I set them.

### The Apple device you are using:
- Device: [iPhone X]
- OS: [ iOS 14 beta 2]

**Comment by mrjackyliang** [comment]
Try setting `removeObsoleteZones` to `false`

**Comment by w1llf0rd** [comment]
Got it thank you! Great job on the plug-in it’s amazing. One more question, some glass break and smoke detectors show as contact sensors instead... is there anyway to fix that?

**Comment by mrjackyliang** [comment]
Yes, someone reported the issue but didn't come through with sending me a picture of the device names.

Log on to __ADT Pulse > System__, and then take a screenshot of all your devices. Then comment below on which zones are displaying incorrectly. I need to add the names to the plugin for them to recognize it correctly.

And, in the meantime, try not to re-organize the accessories until the plugin is updated! Don't want you to do the whole organization again.

**Comment by w1llf0rd** [comment]
The Z7 Bedroom Hallway Smoke detector shows as a contact sensor while the other two (Z6 and Z8) show correctly as a smoke sensor. All of the glass break detectors show as occupancy sensors except the Z41 Nook Glass Detector and the Z2 Master Bedroom Glass Detector which show as contact sensors. Thanks for the quick response!
<img width="528" alt="Screen Shot 2020-07-21 at 2 52 07 PM" src="https://user-images.githubusercontent.com/52221746/88111393-b27d2180-cb62-11ea-9e95-0cddf3830135.png">

**Comment by mrjackyliang** [comment]
Glass break detectors will show as occupancy sensors for now. HomeKit doesn't have glass break support yet (afaik).

**Comment by mrjackyliang** [comment]
Just documenting this:

- `Z7 Bedroom 's Hallway Smoke Detector` detected as contact sensor because `Bedroom` has a `dr` in it.
- `Z41 Nook Glass Detector` detected as contact sensor because "Nook" is part of the `doorWindow` detection.
- `Z2 Master Bedroom Glass Detector` detected as contact sensor because `Bedroom` has a `dr` in it.

**Comment by mrjackyliang** [comment]
@w1llf0rd I am assuming that the sensors with names `Service` are not being added to Homebridge also? They don't seem to be in the list of detectable accessories in the plug-in.

**Comment by w1llf0rd** [comment]
Yes the service sensors are not in homebridge... thanks!

**Comment by knedd** [comment]
Guys,

 

My system shows Glass Detectors in HomeKit.  See attached. 

 

Kevin

**Comment by mrjackyliang** [comment]
@knedd Hi, can you upload the screenshot directly to GitHub? The image attached is not shown here for some reason.

**Comment by knedd** [comment]
My system shows glass breakage detectors
![IMG_1253 (003)](https://user-images.githubusercontent.com/36968126/88117410-0995ed00-cb89-11ea-8a62-714701a968bc.jpg)
.

**Comment by mrjackyliang** [comment]
@knedd Oh. Glass detectors are supported in this plugin. They will just be shown as an occupancy sensor. HomeKit doesn't officially support glass break sensors. Once it does, I will convert it and give instructions on how to upgrade.

**Comment by mrjackyliang** [comment]
@w1llf0rd [v1.8.11](https://github.com/mrjackyliang/homebridge-adt-pulse/releases/tag/v1.8.11) is now available. Before you update to this version, please follow the directions below to prevent your Homebridge from crashing:

1. Set `resetAll` to `true`
2. Restart Homebridge
3. Update to `v1.8.11`
4. Set `resetAll` to `false`
5. Restart Homebridge again

These instructions only apply to you. Anyone else should proceed with the update normally unless their sensors were also wrongly detected in the first place. Let me know if the update is a success, thanks!

**Comment by w1llf0rd** [comment]
Sorry for the late response... got busy yesterday. I updated to 1.8.11 and now it continuously says ADT Pulse - An unknown error occurred. Also the same sensors as before still show as contact sensors.
![5B700AE7-C083-4B59-AEE2-D02915534DD7](https://user-images.githubusercontent.com/52221746/88202175-5a472d80-cbfd-11ea-8d24-d4ff95b98022.png)
![47D0B9F0-FE81-4E35-A50F-FFEEAE2D2E29](https://user-images.githubusercontent.com/52221746/88202181-5d421e00-cbfd-11ea-96a2-5f3f72cd27a8.png)
![2D8544AB-58AB-4AB9-9DF7-B669740BF64A](https://user-images.githubusercontent.com/52221746/88202188-5e734b00-cbfd-11ea-9d5b-435bb8bdc12d.png)
![image](https://user-images.githubusercontent.com/52221746/88202214-67641c80-cbfd-11ea-8835-6f752c2e5940.jpg)

**Comment by mrjackyliang** [comment]
Did you reset all the devices before the upgrade was performed?

**Comment by w1llf0rd** [comment]
I tried but couldn’t find where to set resetAll so I just unadded and readded the bridge... I’m a homebridge noob!

**Comment by mrjackyliang** [comment]
You would have to set the `resetAll` using the configuration in Homebridge. The `README.md` file in the repository should give you examples on how to do so.

**Comment by w1llf0rd** [comment]
Done! Thank you for all your work!

**Comment by mrjackyliang** [comment]
Not a problem! Let me know if the unknown error continues to exist!
