### ISSUE TITLE
Support for Web Portal version 20.0.0-221

### ISSUE THREAD

**Issue by flyingsqu1d** [mrjackyliang/homebridge-adt-pulse#34]
I have this plug-in installed and working well through HOOBS. In the last 48 hours the following entry has started spamming my logs every 30 seconds or so:

7/31/2020, 7:30:26 AM [ADT Pulse] Web Portal version 20.0.0-221 detected. Test plugin to ensure system compatibility...

All functionality seems to be normal. Any chance for an update to remove the warnings in the log?

**Comment by mrjackyliang** [comment]
Will do some internal testing tonight.

The logs are mostly spamming because ADT Pulse tends to switch to the new version and back every time an upgrade is pushed.

But I'll push and update once I get on the new version and do some tests. Thanks for letting me know!

**Comment by mrjackyliang** [comment]
`v1.8.12` is now available!
