### ISSUE TITLE
Arm Instant Mode

### ISSUE THREAD

**Issue by Apple2T4ch** [mrjackyliang/homebridge-adt-pulse#36]
### Is your feature request related to a problem? 
No.

### Describe the solution you'd like.
Arm Instant via Home app. (Instant is when if a sensor trips alarm instanly sounds)

### Describe alternatives you've considered.
Haven't considered any alternatives.

**Comment by mrjackyliang** [comment]
In my knowledge, ADT Pulse doesn't have Arm Instant and HomeKit doesn't have an interface to implement Arm Instant.

Don't think I can bake this feature in, sorry.

**Comment by mrjackyliang** [comment]
Opening this back to determine whether this is a possibility. Could be a different arm name when setting the state.

Possible ideas, have a setting to allow instant modes. Need to physically test the system to see if this is possible
