### ISSUE TITLE
Water Sensor and Cameras Support

### ISSUE THREAD

**Issue by OxfordRancher** [mrjackyliang/homebridge-adt-pulse#38]
### Is your feature request related to a problem? Please describe.
Possible to add support for water sensor and adt cameras? Water sensor and cameras not detected by plugin 

### Describe the solution you'd like:
Include sensor and cameras support in plugin

### Describe alternatives you've considered:

Cameras lower priority 

Water sensor support alternative might be daisy chain via either google or Alexa and ifttt but that would be a workaround

**Comment by mrjackyliang** [comment]
Sorry, the ADT Pulse plugin does not support Z-Wave Integrations.

**Comment by NathanBlais** [comment]
Are the cameras connected through Z-Wave?

**Comment by mrjackyliang** [comment]
Coming back here to ask about the water sensor.
