### ISSUE TITLE
DESCRIBE THE BUG HERE AS SYSTEMATICALLY AS POSSIBLE

### ISSUE THREAD

**Issue by nikunp89** [mrjackyliang/homebridge-adt-pulse#40]
### Describe the bug:
What do you think the problem relates to?

### Steps to reproduce the bug:
1.  Keep getting the error in logs Portal sync stalled cleaning up and resetting s

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.9.3
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v14.15.3
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v1.1.7
```

### Logs related to this bug:
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp?e=ns&partner=adt&e=n
ADT Pulse: Response path matches -> false
ADT Pulse: Portal sync failed.
ADT Pulse: Response path -> /myhome/20.0.0-244/summary/summary.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Site ID -> 200814zb861595
ADT Pulse: Login success.
ADT Pulse: Performing portal sync...
ADT Pulse: Performing portal sync...
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 20.0.0-244
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp?e=ns&partner=adt
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.
[02/01/2021, 23:58:45] [ADT Pulse] Login failed. Trying again...
[02/01/2021, 23:58:45] [ADT Pulse] You have not yet signed in or you have been signed out due to inactivity. Sign in to proceed.
ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 20.0.0-244
[02/01/2021, 23:59:04] [ADT Pulse] Portal sync stalled. Cleaning up and resetting...
ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 20.0.0-244
[02/01/2021, 23:59:25] [ADT Pulse] Portal sync stalled. Cleaning up and resetting...
ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/20.0.0-244/summary/summary.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Site ID -> 200814zb861595
ADT Pulse: Login success.
ADT Pulse: Performing portal sync...
ADT Pulse: Response path -> /myhome/20.0.0-244/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 20.0.0-244
[02/01/2021, 23:59:46] [ADT Pulse] Portal sync stalled. Cleaning up and resetting...
ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/20.0.0-244/summary/summary.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Site ID -> 200814zb861595
ADT Pulse: Login success.
ADT Pulse: Performing portal sync...
[03/01/2021, 00:00:07] [ADT Pulse] Portal sync stalled. Cleaning up and resetting...
ADT Pulse: Performing portal sync...
ADT Pulse: Response path -> /myhome/20.0.0-244/summary/summary.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Site ID -> 200814zb861595
ADT Pulse: Login success.
ADT Pulse: Performing portal sync...

**Comment by mrjackyliang** [comment]
Portal sync stall detection is an intended feature to detect stalled sync progression. It's not a bug.

**Comment by nikunp89** [comment]
Portal sync keeps failing so my accessories aren’t responding in my home app

**Comment by mrjackyliang** [comment]
If the sync keeps stalling, try rebooting your network and the Homebridge server.

Sometimes this will happen for a long period of time, most likely due to ADT itself.
