### ISSUE TITLE
add support for ADT command command

### ISSUE THREAD

**Issue by alyakhov1** [mrjackyliang/homebridge-adt-pulse#44]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. For example, I'm always frustrated when [...]
I have ADT Command not pulse. The current plugin appears to use pulse url and I don't see an option to change it to use ADT control login url

### Describe the solution you'd like:

Please add support for ADT Command and its login URL

### Describe alternatives you've considered:

I don't see an alternative

**Comment by mrjackyliang** [comment]
The ADT Pulse system and the ADT Control system are two different platforms. One is a platform acquired by Alarm.com (Icontrol One, this plugin supports that) and the other is developed by Alarm.com.

In addition, I don't own an ADT Control system to be able to develop a new plugin so this cannot be worked on.
