### ISSUE TITLE
Unable to Detect Sensors

### ISSUE THREAD

**Issue by geoffreyspencer** [mrjackyliang/homebridge-adt-pulse#45]
### Describe the bug:
ADT Pulse for HomeBridge. Only main panel shows up in Apple's HomeKit. None of the others

### Steps to reproduce the bug:
1.  Install the ADT Pulse for HomeBridge
2. Set up username and password
3. Restart HomeBridge
4. Security Panel appears in HomeKit but none of the other sensors
5. Added manually the Door sensors with the exact same name in the ADT Pulse Portal and the correct type
6. Restarted HomeBridge
7. Only Security Panel in the HomeKit.
8. Checked Accessories in HomeBridge, no other ADT sensors.

### Expected behavior:
I get the Security Panel to appear in the HomeBridge and Apple's HomeKit but nothing else. It should be getting all 16 sensors and the Security Panel.

I added a few sensors manually but they still do not show up.

### The Apple device you are using:
- Device: macOS
- OS: 11.3 (Big Sur)

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[5/2/2021, 2:28:58 PM] [ADT Pulse] running on linux (arm)
[5/2/2021, 2:28:58 PM] [ADT Pulse] homebridge-adt-pulse v2.0.2
[5/2/2021, 2:28:58 PM] [ADT Pulse] node v14.16.1
[5/2/2021, 2:28:58 PM] [ADT Pulse] homebridge v1.3.4
```

Found this one too:
[5/2/2021, 2:29:08 PM] [ADT Pulse] Web Portal version 21.0.0-353 detected. Test plugin to ensure system compatibility...

Nothing else in the log

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

Where is the log on Raspberry PI again?

```sh
SAMPLE TEXT
```

**Comment by geoffreyspencer** [comment]
This came up after I submitted my "bug" report:

[5/2/2021, 2:34:44 PM] [ADT Pulse] Security Panel (system-1) changed from "disarmed / all quiet" to "disarmed / motion".
[5/2/2021, 2:34:45 PM] [ADT Pulse] Motion Dining Room (sensor-8) changed from "no motion" to "motion".

**Comment by mrjackyliang** [comment]
I'm curious, can I see a screenshot of your device names? It could be abnormal, as the plugin does detect device types based on their names now.

**Comment by geoffreyspencer** [comment]
I named them manually and they finally came up but not as resources except for the Security Panel. They appear along the top of the HomeKit Home or in their assigned rooms. Personally, I rather have them as resources but this is still workable. I wonder what happens if I remove the manually entries.

**Comment by mrjackyliang** [comment]
I think sensors appearing in their assigned rooms should be a new feature of iOS. I do remember it being all in __Default Room__. If you remove the manual entries, they'll just stop updating. They might also be removed depending on if you have the `removeObsoleteZones` turned on (which is by default).
