### ISSUE TITLE
Looking for Plug in for ADT Control

### ISSUE THREAD

**Issue by sureshv8** [mrjackyliang/homebridge-adt-pulse#46]
### Describe the solution you'd like:
Hello I am looking for plug in for ADT Control.  ADT's new app is called ADT Control the app link is below. This is what ADT calls it as their  future app.  Pulse is being phased out eventually.  Could you please help with a plug in for this? This is the only device i dont have integration with Apple HomeKit.  Please help.

https://apps.apple.com/us/app/adt-control/id1423831457

**Comment by mrjackyliang** [comment]
Hi, I don't have ADT Control currently. Unless someone wants to grant me access to their home for me to develop this plugin, it would be great!

**Comment by sureshv8** [comment]
Jackie, thank you for the reply.  if you explain what the process and how long then I may be able to.

Sent from my iPhone

On May 20, 2021, at 4:49 PM, Jacky Liang ***@***.***> wrote:

﻿

Hi, I don't have ADT Control currently. Unless someone wants to grant me access to their home for me to develop this plugin, it would be great!

**Comment by mrjackyliang** [comment]
That would require me to access your ADT Control account, and months of back testing. I would randomly turn your alarm on and off, require you to place on test mode. Probably not the best idea if you're going to be using your security system.

**Comment by sureshv8** [comment]
Agree.  The system is actively used. May be try to get a system at your end month to month or on eBay. I can chip in to offset the cost.

Sent from my iPhone

On May 20, 2021, at 5:46 PM, Jacky Liang ***@***.***> wrote:

﻿

That would require me to access your ADT Control account, and months of back testing. I would randomly turn your alarm on and off, require you to place on test mode. Probably not the best idea if you're going to be using your security system.

**Comment by mrjackyliang** [comment]
I developed this plugin at home. Unless I am required by ADT to upgrade, I'm probably going to wait it out.

Also there isn't a guarantee that even if I get access to the new system, it's even developable.

**Comment by sureshv8** [comment]
Ok

Sent from my iPhone

On May 20, 2021, at 6:00 PM, Jacky Liang ***@***.***> wrote:

﻿

I developed this plugin at home. Unless I am required by ADT to upgrade, I'm probably going to wait it out.

Also there isn't a guarantee that even if I get access to the new system, it's even developable.
