### ISSUE TITLE
Web Portal version 21.0.0-353 detected. Test plugin to ensure system compatibility...

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#48]
### Describe the bug:
System seams to work just getting waring Web Portal version 21.0.0-353 detected. Test plugin to ensure system compatibility...

### Steps to reproduce the bug:
1. launch home bridge running ads pulse plugin.

### Expected behavior:
no waring message expected and this warning appears.

### The Apple device you are using:
- Device: AppleTV 4K
- OS: TVos 14.x

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[7/1/2021, 9:35:41 PM] [ADT Pulse] running on linux (x64)
[7/1/2021, 9:35:41 PM] [ADT Pulse] homebridge-adt-pulse v2.0.2
[7/1/2021, 9:35:41 PM] [ADT Pulse] node v14.17.2
[7/1/2021, 9:35:41 PM] [ADT Pulse] homebridge v1.3.4
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
Will work on updating it soon!

**Comment by mrjackyliang** [comment]
Version 2.0.3 has been released!
