### ISSUE TITLE
Web Portal version 17.0.0-69 does not match 16.0.0-131

### ISSUE THREAD

**Issue by jlclarkrx** [mrjackyliang/homebridge-adt-pulse#5]
The plugin is working great. Thank you for all your work on this. The logs return "Web Portal version 17.0.0-69 does not match 16.0.0-131" and I noticed that you wanted users to inform you if the web Portal version is changed or updated.

**Comment by mrjackyliang** [comment]
Yes, thank you for the notification! Right now, the website transitions between versions 16 and 17, so I'm going to hold off on the update until the wave is over.

As far as I know, the update is not creating any issues, so you shouldn't have anything to worry about for the moment.

**Comment by mrjackyliang** [comment]
The latest update `v1.2.7` should get rid of the warning messages until the next version is released. Right now, the plugin works with both `17.0.0-69` and `16.0.0-131`. Closing for now!
