### ISSUE TITLE
Login not working since ADT switched to 2FA

### ISSUE THREAD

**Issue by burtherman** [mrjackyliang/homebridge-adt-pulse#55]
Not seeing any accessories since ADT switched

**Comment by mrjackyliang** [comment]
Plugin doesn't work on 2FA. You'd need to create a separate user account to use the plugin again.

**Comment by burtherman** [comment]
How do you mean - does ADT now require 2FA to be active for all accounts? Other plugins work with 2FA after you authenticate with the code like Ring

**Comment by knedd** [comment]
Just establish another account from within the portal and don’t enable 2FA and it will work fine. 

Kevin

Sent via iPhone

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.
