### ISSUE TITLE
ADT Pulse 2FA Causing Issues

### ISSUE THREAD

**Issue by mlw4428** [mrjackyliang/homebridge-adt-pulse#56]
### Describe the bug:
ADT Pulse and their 2FA introduction seems to be interfering with Homebridge.
### Steps to reproduce the bug:
1. Set a mode
2. Mode fails to set silently 

### Expected behavior:
Security panel mode change

### Homebridge information:
Latest homebridge and plugin. Even rebooted. Logs show a failure to sign in, prob related to 2FA.

I did navigate via Raspberry Pi browser and sign in and select to remember device, but that's prob a cookie or session info this plugin doesn't see.

**Comment by mlw4428** [comment]
Continued investigation shows 2FA seems to be per-profile. The iOS Pulse app seems to force you to setup 2FA.

So workaround may exist by setting up a Homebridge specific account WITHOUT 2FA.

Doesn't seem too hard, I'll report back on how it works once I set it up tonight or tomorrow.

**Comment by mrjackyliang** [comment]
Yes, the issue is already solved and pinned above.

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.
