### ISSUE TITLE
ADT Pulse not working

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#58]
I install the plugin on a new bridge, but it is not reading any of my accessories.  I am getting the following message in the logs:

10/2/2021, 8:18:34 AMAdt Pulse BridgeWARNINGunhandled rejection: TypeError: Cannot read property 'match' of null

This is a new problem.  Accessories were appearing just fine until I did a reset.  Reason I did a reset was that one sensor accessory was reading as OPEN even though it was not.  The door was shut and it was appearing as shut in the ADT Pulse app, but appearing as OPEN in the Homebridge plugin.  This was one of 36 sensors in my home.  So I did a reset and now can't get anything to appear!  Please help!!!

**Comment by mrjackyliang** [comment]
Try to follow issue #51. When I did that, that helped the plugin to stop asking for 2FA. If you have already set 2FA, please create another account.

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.
