### ISSUE TITLE
ADT two factor authentication 

### ISSUE THREAD

**Issue by cjwyche95** [mrjackyliang/homebridge-adt-pulse#60]
### Describe the bug: Plug in doesn’t work with adt account with two factor authentication 
What do you think the problem relates to?

### Steps to reproduce the bug:
1. 

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
Please check issue #51

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.
