### ISSUE TITLE
Add ability to use 2FA cookie

### ISSUE THREAD

**Issue by abolians** [mrjackyliang/homebridge-adt-pulse#61]
Folks at HA found a workaround to 2FA by manually inputing the 2FA cookie from an authenticated browser. 
Can you also implement this from your end?

https://github.com/uvjustin/alarmdotcom#two-factor-authentication

**Comment by abolians** [comment]
Thank you. I got the WAR on issue 51 working for now with a new account. But I doubt that it will stick permanently, Although, it has survived a couple of manual HB server reboots. I think ADT pulse uses a similar cookie method to authenticate browsers. I will dig deeper to see if I can expose it. Thank you for the quick response

**Comment by mrjackyliang** [comment]
#51

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.
