### ISSUE TITLE
2 of my sensors are reporting as glass break when they are Door/Window Sensor

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#62]
I have 33 items showing up in ADT pulse homebridge plugin.  2 of those sensors are reading incorrectly.  They are showing correctly on the pulse app though. 2 sensors are showing as glass break when they should be showing as door/window sensors. what level of debugging do I need to show for these sensors or is there a way to manually override sensor type?

For instance when the door is open it is giving me a glass break notification in homebridge/homekit but pulse app is telling me door/window is open properly.

**Comment by mrjackyliang** [comment]
https://github.com/mrjackyliang/homebridge-adt-pulse#manually-override-sensors
