### ISSUE TITLE
MFA Requirement Breaks ADT Pulse Plugin

### ISSUE THREAD

**Issue by cyberpower678** [mrjackyliang/homebridge-adt-pulse#64]
The plug-in no longer seems able to get a read on the security system and accessories.  Presumably, this has something to do with the new 2FA.  Despite it being deactivated, it just gets an error for every action it attempts to do.

**Comment by kmnedd** [comment]
Check out the comments in closed issue 51 for a solution.

**Comment by cyberpower678** [comment]
None of the comments solve my issue.  The issue happened on it’s own out of the blue perhaps ADT is now forcing MFA.  So the fingerprint option would be the only viable option.  When will it be merged?

**Comment by mrjackyliang** [comment]
Have you tried the fingerprint option yet? I haven't had the time to work on it, so it might take a while before I review the code.

**Comment by mrjackyliang** [comment]
And also, ADT Pulse is not working on my side as well.

**Comment by mrjackyliang** [comment]
Working on the update now! Thanks @Danimal4326!

**Comment by mdombrowski13** [comment]
Can't wait for a fix =). This is the best plugin for Homebridge I've used!  I'm happy to beta test for you if you need it as I've been broke for a few days now too.

```
ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/22.0.0-233/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 22.0.0-233
ADT Pulse: Response path -> /myhome/22.0.0-233/mfa/mfaSignIn.jsp?workflow=initialSetup&shouldForceMfaSetup=true
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.
```

**Comment by cyberpower678** [comment]
Same.  This is a critical plug in for me.

**Comment by mrjackyliang** [comment]
`v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.

**Comment by cyberpower678** [comment]
> `v2.1.0` is now released. Instructions on how to obtain the `fingerprint` are inside the `README.md` file.

How do I get it on Hoobs?  It's still showing 2.0.4 as the latest?  I'm using Hoobs 4.

**Comment by tarunprakashsingh** [comment]
How do I get it on Hoobs? It's still showing 2.0.4 as the latest? I'm using Hoobs 4.

**Comment by mrjackyliang** [comment]
HOOBS get their packages from
npm. Should reflect the same as anywhere you install it from.
