### ISSUE TITLE
My Fingerprint does not end in "=="

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#66]
### Describe the bug:
in Step 7 not all fingerprints end in equals sign.  My fingerprint does not and it works.

Readme.md states: 

> Configure 2-Factor Authentication
> 
> With the recent updates, ADT Pulse now requires 2-factor authentication for your account. In the near future, this fingerprint will be required.
> 
> Open a Chrome browser tab
> Open Developer Tools (using View ➜ Developer ➜ Developer Tools menu)
> Click on the Network tab (make sure Preserve log checkbox is checked)
> In the filter box, enter signin.jsp
> Go to https://portal.adtpulse.com or https://portal-ca.adtpulse.com and login to your account
> Click on the network call (beginning with signin.jsp) appearing in the DevTools window
> In the Headers tab, under Form Data, copy the entire fingerprint (ending in =)
> Paste the copied text into the fingerprint field into your config.json
> 

### Steps to reproduce the bug:
1. Follow instructions to get fingerprint.  verify in form data that fingerprint does not end in "=". 
2. Enter figure print into Homebridge plugin. 
3. verify functioning plugin with log file.

### Expected behavior:
Expected to find = at end if finger print.  None shown on my debug console.

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

**Comment by mrjackyliang** [comment]
Odd. Mine ends in `==`. Are you seeing something like `%3D%3D`? If you are, replace them with `==`.

**Comment by mdombrowski13** [comment]
No mine does not end in  %3D%3D either.  it ends in 6 ASCII letters and numbers no symbols.

**Comment by mrjackyliang** [comment]
Are you able to send the beginning and the end of the fingerprint here? Could help me determine the fingerprint. Don't send the whole thing though.

**Comment by mdombrowski13** [comment]
@mrjackyliang I can send you some of that information personally but don't want to post anything of a security key online for all of perpetuity in GIT

**Comment by mrjackyliang** [comment]
> @mrjackyliang I can send you some of that information personally but don't want to post anything of a security key online for all of perpetuity in GIT

Sure. You can send it to `mrjackyliang@icloud.com`
