### ISSUE TITLE
Provide a test login function on the plug-in settings page

### ISSUE THREAD

**Issue by fallingrock** [mrjackyliang/homebridge-adt-pulse#69]
### Is your feature request related to a problem? Please describe.
It would be useful if the settings page had the ability to test the login info (id, password, & fingerprint) so you don't have to risk locking out your account due to bad authentication.

**Comment by mrjackyliang** [comment]
Ahh right. There is a test file that I didn't populate yet. Will keep this open until I have time to make it work.

**Comment by mrjackyliang** [comment]
`v2.1.2` should have the test files updated with fingerprint support!
