### ISSUE TITLE
Trigger Alarm in ADT when Third-Party Accessories are Triggered

### ISSUE THREAD

**Issue by jlclarkrx** [mrjackyliang/homebridge-adt-pulse#7]
Is there a way to add the siren as a supported hardware device?

**Comment by mrjackyliang** [comment]
Is the siren a separate accessory attached to ADT Pulse, or is it part of the security system?

**Comment by jlclarkrx** [comment]
It is a part of the security system.

**Comment by mrjackyliang** [comment]
Technically, it isn't possible because there is no official sensor that's linked with the system. What's your thought on adding a siren to the plugin?

**Comment by jlclarkrx** [comment]
I assumed that was going to be the case but thought I would ask. If it was able to be added as a siren, I was going to add it to some automatons in homekit that are not part of the ADT system. Thank you for all your work on this!

**Comment by mrjackyliang** [comment]
From my understanding, do you want accessories to be controlled when the Siren rings? If so, the Home app already allows that.

You can enable it like this:
1. Open Home app.
2. Tap on the __Automation tab__.
3. Tap __+__ (top right corner).
4. Tap __An Accessory is Controlled__.
5. Tap __Security Panel__.
6. Tap __Next__.
7. Tap __Triggers__.
8. Tap __Next__.
9. Select the accessories you want to react to.
10. Voila!

**Comment by jlclarkrx** [comment]
Thank you. That is good to know but I was looking to do the opposite. I have homekit enabled carbon monoxide/smoke detectors that are separate from my ADT Pulse system. I was hoping to have the ADT Pulse siren activated when these separate CO/smoke detectors are triggered. In the Home app, when one of these detectors is triggered the only automation options for the security panel are Home/Away/Night/Off (there is no Trigger option going the other direction).

**Comment by mrjackyliang** [comment]
I see. I'll definitely keep a lookout of a Panic button if available in ADT Pulse. I know the Security Panel has a Fire and Police button on there.

**Comment by mrjackyliang** [comment]
I just did a test on the __fire__ and __police__ buttons on the panel and I found out there isn't a way to trigger the statuses remotely. So this feature cannot be implemented. Sorry! Closing ticket for now.

#### Fire
- The status changes from `Disarmed` to `FIRE ALARM` on the web portal.
- The alarm rings every second or so.
- I have not found a keyword to trigger the alarm remotely.

#### Police
- The status doesn't change on the web portal.
- The alarm rings continuously.
- I have not found a keyword to trigger the alarm remotely.
