### ISSUE TITLE
ADT Pulse plugin 2.1.1 is not logging into portal.adtpulse.com (220.0.0-233)

### ISSUE THREAD

**Issue by jim-at-miramontes** [mrjackyliang/homebridge-adt-pulse#70]
### Describe the bug:
I lost access to my ADT stuff in Homebridge, and found that its attempt to log into the ADT portal was failing.

### Steps to reproduce the bug:
1. Start Homebridge and watch its attempt to connect to the ADT Pulse backend fail.  (Sorry, I'm not sure what else to say here.)

### Expected behavior:
Start Homebridge and watch its attempt to connect to the ADT Pulse backend not fail.

### The Apple device you are using:
- Device: MacBook Pro
- OS: 12.0.1, with Safari 15.1 or Chrome 95.0.4638.69
- also an iPad Pro running iOS 15.1

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[08/11/2021, 10:49:54] [ADT Pulse] running on linux (arm)
[08/11/2021, 10:49:54] [ADT Pulse] homebridge-adt-pulse v2.1.1
[08/11/2021, 10:49:54] [ADT Pulse] node v14.17.4
[08/11/2021, 10:49:54] [ADT Pulse] homebridge v1.3.5
```

### Logs related to this bug:
```sh
running with debug = 50:

ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/22.0.0-233/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 22.0.0-233
ADT Pulse: Response path -> /myhome/22.0.0-233/access/signin.jsp
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.

It then repeats this attempt, over and over again.  Occasionally, however, it changes to this:

ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/22.0.0-233/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 22.0.0-233
ADT Pulse: Response path -> /myhome/22.0.0-233/mfa/mfaSignIn.jsp?workflow=challenge
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.

sort of alternating between the mfa path and the non-mfa path
```

My (slightly hacked) config file, with fingerprint:

```
{
    "bridge": {
        "name": "Homebridge 7611",
        "username": "0E:4D:XX:XX:XX:11",
        "port": 51767,
        "pin": "376-XX-XX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "tokentokentoken",
            "platform": "Ring"
        },
        {
            "name": "Nest",
            "access_token": "tokentokentoken",
            "platform": "Nest"
        },
        {
            "name": "ADT Pulse",
            "username": "xxx@yyy.com",
            "password": "xxxxxx",
            "fingerprint": "veryveryverylongstringofcharacters",
            "country": "us",
            "logLevel": 50,
            "logActivity": true,
            "removeObsoleteZones": true,
            "resetAll": false,
            "platform": "ADTPulse"
        }
    ]
}
```

Also: I'm having trouble logging into portal.adtpulse.com via a regular browser on the Mac: I'm getting a 429 Too Many Requests fail/block (see also https://github.com/mrjackyliang/homebridge-adt-pulse/issues/51).  No sign of that error here, but my Raspberry Pi is showing the same IP address as the Mac.  I'm trying to get that resolved with ADT; it ?could? happen...

LMK if you need more details.  The plugin used to work very nicely, but, a few days ago, it just stopped...

**Comment by mrjackyliang** [comment]
Did you enable 2-factor authentication yet and save the browser? If you did, you should not need to re-authenticate even with the fingerprint.

**Comment by jim-at-miramontes** [comment]
All turns out to be well -- in any case, I'm back up and running.  2FA was indeed set up, but there may have been some confusions with accounts and fingerprints.  

Meanwhile, I'll note that my setup is working with the apparently new 22.0.0-233 endpoint at ADT; the doc at https://github.com/mrjackyliang/homebridge-adt-pulse only mentions 20.0.0-221 and 20.0.0-244, so I guess this is good news.  Thanks for the help!
