### ISSUE TITLE
Sensors stopped loading after update

### ISSUE THREAD

**Issue by Mattapoisett** [mrjackyliang/homebridge-adt-pulse#71]
Hello, 

First I want to thank you all for getting the 2FA issue fixed.  I finally got around to performing the update and updating my Node.js. However when I got it up and running after the update, the plugin doesn't seem to load the sensors.  When I reboot the only reference I see to to ADT Pulse is this:
[ADT Pulse] running on linux (x64)
[ADT Pulse] homebridge-adt-pulse v2.1.1
[ADT Pulse] node v16.13.0
[ADT Pulse] homebridge v1.3.5

I even performed a "resetALL": true, with no luck. Though I'm not sure it ran since there was no info about it in the l Homebridge  logs.  What should I look for next to resolve this issue?

**Comment by knedd** [comment]
Did you check to see if you IP address is being blocked by ADT? Try logging in to the portal from the same machine. 

Kevin

Sent via iPhone

**Comment by Mattapoisett** [comment]
Funny you should mention it.  I was having issues getting to the portal.adtpulse.com .  When the page loaded, it told me I was blocked.  I contacted ADT, they concluded my ISP was doing the blocking.  I resorted to using a VPN to log into my web client.  I didn't think about it affecting the HomeBridge.  Any suggestions for getting my IP address back on the white list?

**Comment by mrjackyliang** [comment]
> Funny you should mention it. I was having issues getting to the portal.adtpulse.com . When the page loaded, it told me I was blocked. I contacted ADT, they concluded my ISP was doing the blocking. I resorted to using a VPN to log into my web client. I didn't think about it affecting the HomeBridge. Any suggestions for getting my IP address back on the white list?

It's actually a block done by Alarm.com. The trick is to set the correct configuration, and then stop Homebridge for about 30 mins. Then reboot it, everything should fall into place.

**Comment by Mattapoisett** [comment]
> > Funny you should mention it. I was having issues getting to the portal.adtpulse.com . When the page loaded, it told me I was blocked. I contacted ADT, they concluded my ISP was doing the blocking. I resorted to using a VPN to log into my web client. I didn't think about it affecting the HomeBridge. Any suggestions for getting my IP address back on the white list?
> 
> It's actually a block done by Alarm.com. The trick is to set the correct configuration, and then stop Homebridge for about 30 mins. Then reboot it, everything should fall into place.

Well I had put in the fingerprint key yesterday. when It didn't work I reached out here,  I couldn't think of any other config which needed to be changed.  I shut it down for just over an hour and when I brought it up, it still want connecting properly.  Do I need to get another key and put is in the JSON file, then immediately reboot?  or is there something else I need to look for?

**Comment by mrjackyliang** [comment]
> > > Funny you should mention it. I was having issues getting to the portal.adtpulse.com . When the page loaded, it told me I was blocked. I contacted ADT, they concluded my ISP was doing the blocking. I resorted to using a VPN to log into my web client. I didn't think about it affecting the HomeBridge. Any suggestions for getting my IP address back on the white list?
> > 
> > 
> > It's actually a block done by Alarm.com. The trick is to set the correct configuration, and then stop Homebridge for about 30 mins. Then reboot it, everything should fall into place.
> 
> Well I had put in the fingerprint key yesterday. when It didn't work I reached out here, I couldn't think of any other config which needed to be changed. I shut it down for just over an hour and when I brought it up, it still want connecting properly. Do I need to get another key and put is in the JSON file, then immediately reboot? or is there something else I need to look for?

You can try, but if it worsens, better to contact your ISP and request an IP address change.

**Comment by mrjackyliang** [comment]
Closing this for now. I think this problem is solved over time. Simply by stopping Homebridge or the plugin itself for an hour or so, and then reboot the plugin.

**Comment by Mattapoisett** [comment]
Thanks for all the help. I was finally able to get everything to line up and work with a fingerprint.
