### ISSUE TITLE
ADT Pulse For Homebridge Sensor Refresh Eliminates HomeKit Configuration 

### ISSUE THREAD

**Issue by hapinstance** [mrjackyliang/homebridge-adt-pulse#72]
### Describe the bug:
Occasionally the homebridge plugin seems to perform a refresh of the sensors from the Pulse website.  When this occurs, any modifications made to the sensors within HOOBS or HomeKit are lost.  For example, if a default sensor type is changed from 'sensor' to 'door', or a sensor is moved into a room within Homekit, these changes are be lost as the sensor is removed from homebridge during the refresh and added back to homebridge in its default state and location.  

### Steps to reproduce the bug:
1. Wait for the refresh.  

### Expected behavior:
Once sensors are added to the system I would expect them to remain in the system.  Could the refresh be disabled?  Could it check the sensor before deleting it to see if it was already in the system?   

### The Apple device you are using:
- N/A

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
ADT Pulse Bridge ADT Pulse running on linux (arm)
ADT Pulse Bridge ADT Pulse homebridge-adt-pulse v2.1.1
ADT Pulse Bridge ADT Pulse node v14.18.1
ADT Pulse Bridge ADT Pulse homebridge v1.3.0
```

### Logs related to this bug:
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Preparing to remove zone (sensor-13) accessory...
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Removing accessory... Basement Door (sensor-13)
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Preparing to remove zone (sensor-27) accessory...
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Removing accessory... 2nd Bedroom Window 27 (sensor-27)
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Preparing to remove zone (sensor-26) accessory...
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Removing accessory... 2nd Bedroom Window 26 (sensor-26)
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Preparing to remove zone (sensor-25) accessory...
11/11/2021, 5:34:23 AM ADT Pulse BridgeADT Pulse Removing accessory... 2nd Bedroom Window (sensor-25)
...
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Preparing to add zone (sensor-25) accessory...
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Adding accessory... 2nd Bedroom Window (sensor-25)
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Preparing to add zone (sensor-26) accessory...
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Adding accessory... 2nd Bedroom Window 26 (sensor-26)
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Preparing to add zone (sensor-27) accessory...
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Adding accessory... 2nd Bedroom Window 27 (sensor-27)
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Preparing to add zone (sensor-13) accessory...
11/11/2021, 5:34:25 AM ADT Pulse BridgeADT Pulse Adding accessory... Basement Door (sensor-13)

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
Please check [the readme](https://github.com/mrjackyliang/homebridge-adt-pulse#remove-obsolete-zones)

**Comment by hapinstance** [comment]
Thank you!
