### ISSUE TITLE
ADT Pulse accessories keep resetting

### ISSUE THREAD

**Issue by cyberpower678** [mrjackyliang/homebridge-adt-pulse#73]
### Describe the bug:
All accessories related to my security system are resetting back to their default room, and all automations keep disappearing, despite the REMOVE OBSOLETE ZONES not being checked.

### Steps to reproduce the bug:
1. Use Pulse, watch it reset at random.

### Expected behavior:
All zones should be left as is, as well as all automations set up for it.

### The Apple device you are using:
- Device: All of them
- OS: The latest on all devices

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

Log file too large.  It's cut off.

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
11/29/2021, 4:41:01 PM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
11/29/2021, 7:53:19 PM Adt Pulse Bridge ADT Pulse WARNING Login failed. Trying again...
11/29/2021, 7:53:19 PM Adt Pulse Bridge ADT Pulse WARNING Sign In unsuccessful. Try again. Check your Caps Lock key.
11/29/2021, 7:56:56 PM Adt Pulse Bridge ADT Pulse WARNING Portal sync stalled. Cleaning up and resetting...
11/29/2021, 10:20:49 PM Adt Pulse Bridge ADT Pulse WARNING Login failed. Trying again...
11/29/2021, 10:20:49 PM Adt Pulse Bridge ADT Pulse WARNING Sign In unsuccessful. Try again. Check your Caps Lock key.
11/29/2021, 10:21:01 PM Adt Pulse Bridge ADT Pulse ERROR Login failed more than 2 times. Portal sync restarting in 10 minutes...
11/29/2021, 10:21:01 PM Adt Pulse Bridge ADT Pulse ERROR Sign In unsuccessful. Try again. Check your Caps Lock key.
11/29/2021, 10:37:27 PM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
11/30/2021, 1:07:54 AM Adt Pulse Bridge ADT Pulse ERROR An unknown error occurred.
11/30/2021, 8:08:47 AM Adt Pulse Bridge ADT Pulse WARNING Portal sync stalled. Cleaning up and resetting...
11/30/2021, 9:12:29 AM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
11/30/2021, 9:56:06 AM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
11/30/2021, 11:46:51 AM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
11/30/2021, 4:10:21 PM Adt Pulse Bridge ADT Pulse WARNING Portal sync stalled. Cleaning up and resetting...
11/30/2021, 4:12:16 PM Adt Pulse Bridge ADT Pulse ERROR Get zone status failed.
11/30/2021, 4:12:16 PM Adt Pulse Bridge ADT Pulse ERROR Error: connect ETIMEDOUT 216.250.136.209:443
11/30/2021, 5:18:57 PM Adt Pulse Bridge ERROR [Adt Pulse Bridge 6288@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
```

**Comment by mrjackyliang** [comment]
Have you transitioned to use 2FA and fingerprint?

**Comment by cyberpower678** [comment]
Yes.  MFA works fine.

**Comment by mrjackyliang** [comment]
Can you send over your configuration, omitting the username, password, and fingerprints?

**Comment by mrjackyliang** [comment]
Looks like this issue went stale. Let me know if the same issue comes back.

**Comment by cyberpower678** [comment]
Is there any update to this?  I haven't heard anything in the last week.  This issue is happening 3 times a day for me now.

**Comment by cyberpower678** [comment]
{
    "platform": "ADTPulse",
    "name": "ADT Pulse",
    "username": "secret",
    "password": "secret",
    "country": "us",
    "logActivity": true,
    "fingerprint": "secret"
}

**Comment by mrjackyliang** [comment]
You didn't turn on Remove Obsolete Zones

**Comment by cyberpower678** [comment]
Isn’t that the point?

**Comment by mrjackyliang** [comment]
I don't see the setting there. That means it is set to `on`

**Comment by cyberpower678** [comment]
Then I can explain what’s going on.  It’s off in the UI by default, but since it’s not defined in the JSON by default, it’s defaulting to ON despite what the UI is indicating.

**Comment by cyberpower678** [comment]
I explicitly defined the option in the JSON to false so I’ll observe and see what happens.

**Comment by mrjackyliang** [comment]
Could just be a new installation. I can try to replicate to see if that happens
