### ISSUE TITLE
Could you add support for doorbells?

### ISSUE THREAD

**Issue by hapinstance** [mrjackyliang/homebridge-adt-pulse#75]
The current system only picks up certain types of sensors by default.  In some cases, I can add sensors (such as water detectors) via the "Override Sensors" section in the config file.  However, it does not appear to be possible to add doorbell objects to the list.  This may be a result of the fact that they are not listed in the "sensors" section on the Pulse page, or that they are just so different that they have not been enabled yet.  Being able to capture doorbell ring events in automation sequences would be quite useful.  

Thank you so much for providing this plugin!

**Comment by mrjackyliang** [comment]
Is the doorbell sensor an official ADT sensor or is it linked via Z-Wave? If it is Z-Wave, it is better to use an alternative plugin instead for better support.

**Comment by hapinstance** [comment]
It is an ADT DBC835-ADT Doorbell installed and supplied by ADT into their system.  It does show up in Pulse, but in the “Cameras and Doorbells” section of the system tab.  The Pulse app is the only visibility I have to the device.  As for Z-Wave, that would make sense, but I can’t independently confirm it.

**Comment by mrjackyliang** [comment]
Ahh, those are Z-Wave devices. Smart devices aren't supported in this plugin because of the lack of API support.

**Comment by mrjackyliang** [comment]
Hi, going through all of the issues here in Github! Can you tell me more info about the water sensor you have?
