### ISSUE TITLE
DESCRIBE THE BUG HERE AS SYSTEMATICALLY AS POSSIBLE

### ISSUE THREAD

**Issue by mmdlcab** [mrjackyliang/homebridge-adt-pulse#78]
### Describe the bug:
Trying to get the ADT Pulse plugin to work with Homebridge.  

### Steps to reproduce the bug:
1. Configured the plugin as described but can not find the Fingerprint item listed in the description.  There is no Form Data section listed in the headers when I use the Chrome Developers tools as stated.  There are 3 signin.jsp calls showing in the list.  None of those calls contain the Form Data section.  I see the below in the Homebridge logs

2. ADT Pulse: Internet connection is offline or "https://portal.adtpulse.com" is unavailable.
[12/30/2021, 10:51:08 AM] [ADT Pulse] An unknown error occurred.

3.  Digging through many things in the developer tools I did find one reference to finger print, but the string is crazy long,  It was 3243 characters long.  I can provide that string if it would help you.  Inserting that string into the config.json did not help and I really did not expect it too.

### Expected behavior:
I would assume, that the ADT plugin would work, but without the fingerprint, I get the above error.  

### The Apple device you are using:
- MacBook Pro (2019) macOS Monterey version 12.1
- 
### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```
[12/30/2021, 10:49:32 AM] [ADT Pulse] running on darwin (x64)
[12/30/2021, 10:49:32 AM] [ADT Pulse] homebridge-adt-pulse v2.1.2
[12/30/2021, 10:49:32 AM] [ADT Pulse] node v16.13.0
[12/30/2021, 10:49:32 AM] [ADT Pulse] homebridge v1.3.9
Setup Payload:
X-HM://0024TX4F4AEJH
Enter this code with your HomeKit app on your iOS device to pair with 
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
ADT Pulse: Internet connection is offline or "https://portal.adtpulse.com" is unavailable.
[12/30/2021, 10:49:38 AM] [ADT Pulse] An unknown error occurred.

above error repeats over and over.  Not finding any other messages in the log
```

**Comment by mrjackyliang** [comment]
The fingerprint is very long. I assume it's that block of text. Please don't send it over, it is like a password.
