### ISSUE TITLE
LOG IN TROUBLE

### ISSUE THREAD

**Issue by oneill2142** [mrjackyliang/homebridge-adt-pulse#79]
Greetings Jacky,

We were communicating on a previous post and you asked that I move the request to a new post so starting one here. 

I am new to Hoobs and Homekit, learning as I go. I have Ring and MyQ running through Hoobs, but I just cannot seam to get ADT Pulse right. I have found many of the steps below and attemped to add them to Hoobs but still failing and I cannot find the right step. 

Comments in CAPS BELOW

Open a Chrome browser tab (under Incognito mode) - DONE
Open Developer Tools (using View ➜ Developer ➜ Developer Tools menu) - DONE
Click on the Network tab (make sure Preserve log checkbox is checked) - DONE
In the filter box, enter signin.jsp?networkid=     DONE
Go to https://portal.adtpulse.com or https://portal-ca.adtpulse.com and login to your account DONE

Here is where things become somewhat foreign? 
Click Request Code, type in the requested code, and then click Submit Code - _
****NO IDEA WHERE THIS IS ON THE ADT WEBSITE. REQUEST CODE IS NOT PRESENT ANYWHERE IN THE TABS.****_ 

Click Trust this device and name the device Homebridge
Click Save and Continue
Click Sign Out in the top right corner of the webpage
Login to your account (once again)
**HAVENT TAKE THESE STEPS AS I COULD NOT COMPLETE THE PREVIOUS**

Click on the network call (beginning with signin.jsp?networkid=) appearing in the DevTools window. Select the last one.
In the Payload tab, under Form Data, copy the entire fingerprint (after fingerprint:, do not include spaces)
**I CAN LOCATE THIS NOW, AND HAVE COPIED THE FINGERPRINT AS WELL AS MY USER NAME AND PASSWORD INTO HOOBS, BUT HONESTLY UNCLEAR**

Paste the copied text into the fingerprint field into your config.json
**IS IT BEST TO ADD USERNAME, ADD PASSWORD AND FINGERPRINT INTO THE MAIN PAGE, OR TO GO TO THE DETAILS SECTION WHERE I TYPE IN THE "CODE" AND COMPLETE THE ENTIRE ENTRY? I HAVE TRIED BOTH WITH NO SUCCESS**

Close the Chrome window (DO NOT sign out)
**DID THIS PREVIOUSLY AND NO IMPACT**

Honestly ... lost on this. Find a few new things each day, but still not getting this to Homekit. I was wondering are their any video tutorials on completing this step by step perhaps? Also, wondering if my Fingerprint is too long or if I have one digit, comma, or equals sign I shouldnt have?

Thank you
oneill2142

**Comment by mrjackyliang** [comment]
Did you previously set 2-factor authentication already? If you did not, please set it up and try the instructions again.

**Comment by oneill2142** [comment]
Honestly not sure, I had one method verified on the app which showed SMS and my number, I have since added a second method using my email,

**Comment by mrjackyliang** [comment]
Does it give you an option to request code for either methods? The first set of instructions are just about logging in and out

**Comment by oneill2142** [comment]
Actually ... this morning it is FINALLY showing up in my Hoobs and homekit! I going to go with that for now! Thanks for the time

**Comment by mrjackyliang** [comment]
Nice! Goad you got it working :) Going to close this for now
