### ISSUE TITLE
Sensors stop reporting after some time until reboot

### ISSUE THREAD

**Issue by jastorino82** [mrjackyliang/homebridge-adt-pulse#80]
I have noticed lately that after homebridge has been up a while, door and window sensors stop reporting change in state until a reboot. After that, it works.

When the problem occurs, the change is being reported successfully in the ADT Pulse app. HomeBridge logs seem to show sync is successful during this time, but no changes are shown to the sensor in HomeBridge / HomeKit. For example, if I open a door with a contact sensor, Pulse shows it open, but HomeBridge never shows the change.

When the problem occurs, the panel continues to respond fine and show state changes in HomeBridge and HomeKit.

**Comment by mrjackyliang** [comment]
This actually happened to me a while ago. Going to check what's going on.

**Comment by jastorino82** [comment]
Thanks Jackie! The first time it happened, I brushed it off as a fluke, but now I have seen it 3 times. Please let me know if there is any info I can provide that would help, and thanks again for this great plugin.

**Comment by mrjackyliang** [comment]
Sometimes, non-responsiveness will happen because this plugin does not communicate using their official API.

If I don't see any error, usually I'd just reboot Homebridge and call it a day.

**Comment by mrjackyliang** [comment]
Other than some delays, I haven't seen any errors from the plugin as of now. Could be just platform-related adjustments that are out of my control.

Do you have two-factor authentication? Could be worth refreshing the token again and seeing if it happens further. I'll close this issue, but if it keeps happening again, make sure to send in the logs and I'll re-open this issue for an investigation.

**Comment by jastorino82** [comment]
I do have the mandatory 2FA on. However, if it was a token issue, I think it would be quite binary, like it would or would not work, which is not the case.

Sent from my iPhone

On Mar 29, 2022, at 12:11 PM, Jacky Liang ***@***.***> wrote:

﻿

Closed #80<https://github.com/mrjackyliang/homebridge-adt-pulse/issues/80>.

**Comment by mrjackyliang** [comment]
It really depends. The ADT Pulse plugin doesn't directly interact with icontrol One's API so if there were minor glitches from time to time, I would not be able to debug it.
