### ISSUE TITLE
Get ADT Camera statuses

### ISSUE THREAD

**Issue by pruveit** [mrjackyliang/homebridge-adt-pulse#81]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. For example, I'm always frustrated when [...] I am unable to see my ADT cameras in HomeKit.

### Describe the solution you'd like:

I would love to be able to see my ADT cameras in HomeKit.

### Describe alternatives you've considered:

Even if I couldn’t see the cameras, I would love to see that the cameras were offline and maybe when they have returned back online.

Thank you so very much.

JP

**Comment by mrjackyliang** [comment]
I can try to see if I can get camera statuses. Note that I don't currently stay in a location with an ADT system so this'll take a while.

**Comment by mrjackyliang** [comment]
Tried it, but up to date statuses don't always show up
