### ISSUE TITLE
Incompatible with Node.js 16.15.1

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#83]
I updated my system to Node.js 16.15.1 and the plugin stopped working. Went back to Node.js 16.15.0 and it worked again.

Update - I am now getting this message in the log:

 [ADT Pulse] Portal sync stalled. Cleaning up and resetting...

**Comment by mrjackyliang** [comment]
Plugin sync stalling is a common occurrence unrelated to the Node update. Did you receive any other noticed or bugs?

**Comment by mrjackyliang** [comment]
Didn't seem to get any other related logs so I'll just close this issue for now.

**Comment by knedd** [comment]
No.

So nothing to worry about?

Kevin

From: Jacky Liang ***@***.***>
Date: Tuesday, June 7, 2022 at 11:06 AM
To: mrjackyliang/homebridge-adt-pulse ***@***.***>
Cc: Kevin Nedd ***@***.***>, Author ***@***.***>
Subject: Re: [mrjackyliang/homebridge-adt-pulse] Incompatible with Node.js 16.15.1 (Issue #83)

Plugin sync stalling is a common occurrence unrelated to the Node update. Did you receive any other noticed or bugs?

**Comment by mrjackyliang** [comment]
Nope, sounds normal to me for now.
