### ISSUE TITLE
Unable to arm security panel using an automation

### ISSUE THREAD

**Issue by maximilanna** [mrjackyliang/homebridge-adt-pulse#88]
Automations are not able to arm away or arm stay. I.e. I can't have the system arm automatically when everyone left the house or at a certain time (i.e. night time).

**Comment by mrjackyliang** [comment]
Are you able to manually arm and disarm?

**Comment by maximilanna** [comment]
> Are you able to manually arm and disarm?

Yes absolutely

**Comment by mrjackyliang** [comment]
If that's the case, the issue you're having isn't related to the plugin. It's HomeKit's security that's causing the issue.

**Comment by maximilanna** [comment]
What do you mean homekit's security? There is no setting within homekit to adjust security for the panel. I believe what you're referring to is secure requests but that doesnt appear to be the case.

**Comment by mrjackyliang** [comment]
Are you having errors in Homebridge? 

Automatic arming/disarming won't work without the phone asking you if you want to arm/disarm. If you do it through time, you have to set the days active as well.
