### ISSUE TITLE
Device Status

### ISSUE THREAD

**Issue by knedd** [mrjackyliang/homebridge-adt-pulse#9]
{"items":[{"state":{"icon":"devStatMotion","statusTxt":"Front Hall Motion - Motion\nLast Activity: Today 1:09 PM","activityTs":1575828569066},"deprecatedAction":"launchDetailsWindow('RnJvbnQgSGFsbCBNb3Rpb24=','1')","id":"sensor-26","devIndex":"22VER1","name":"Front Hall Motion","tags":"sensor,motion"},{"state":{"icon":"devStatOK","statusTxt":"2nd Floor Smoke - Okay\nLast Activity: 10/13 5:35 AM","activityTs":1539423329326},"deprecatedAction":"launchDetailsWindow('Mm5kIEZsb29yIFNtb2tl','672')","id":"sensor-16","devIndex":"25VER1","name":"2nd Floor Smoke","tags":"sensor,fire"},{"state":{"icon":"devStatOK","statusTxt":"Basement Door - Closed\nLast Activity: 11/17 6:54 PM","activityTs":1574034847210},"deprecatedAction":"launchDetailsWindow('QmFzZW1lbnQgRG9vcg==','504')","id":"sensor-32","devIndex":"21VER1","name":"Basement Door","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Basement Gas Detector - Okay\nLast Activity: 5/18 11:16 AM","activityTs":1526656600873},"deprecatedAction":"launchDetailsWindow('QmFzZW1lbnQgR2FzIERldGVjdG9y','672')","id":"sensor-68","devIndex":"26VER1","name":"Basement Gas Detector","tags":"sensor,co"},{"state":{"icon":"devStatOK","statusTxt":"Basement Window - Closed\nLast Activity: 1/31 8:52 AM","activityTs":1391176322389},"deprecatedAction":"launchDetailsWindow('QmFzZW1lbnQgV2luZG93','672')","id":"sensor-19","devIndex":"15VER1","name":"Basement Window","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Family Window Basement - Closed\nLast Activity: 9/29 11:51 PM","activityTs":1506743491722},"deprecatedAction":"launchDetailsWindow('RmFtaWx5IFdpbmRvdyBCYXNlbWVudA==','672')","id":"sensor-21","devIndex":"17VER1","name":"Family Window Basement","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Front Door - Closed\nLast Activity: 12/2 12:58 PM","activityTs":1575309484019},"deprecatedAction":"launchDetailsWindow('RnJvbnQgRG9vcg==','168')","id":"sensor-2","devIndex":"10VER1","name":"Front Door","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Garage Door - Closed\nLast Activity: Today 12:54 PM","activityTs":1575827645846},"deprecatedAction":"launchDetailsWindow('R2FyYWdlIERvb3I=','1')","id":"sensor-4","devIndex":"12VER1","name":"Garage Door","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Kitchen Door - Closed\nLast Activity: Today 12:52 PM","activityTs":1575827572592},"deprecatedAction":"launchDetailsWindow('S2l0Y2hlbiBEb29y','1')","id":"sensor-3","devIndex":"11VER1","name":"Kitchen Door","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Kitchen Glass Detector - Okay\nLast Activity: 12/2 6:46 PM","activityTs":1575330408733},"deprecatedAction":"launchDetailsWindow('S2l0Y2hlbiBHbGFzcyBEZXRlY3Rvcg==','168')","id":"sensor-28","devIndex":"23VER1","name":"Kitchen Glass Detector","tags":"sensor,glass"},{"state":{"icon":"devStatOK","statusTxt":"Kitchen Heat Detector - Okay\nLast Activity: 9/30 2:59 PM","activityTs":1380567599214},"deprecatedAction":"launchDetailsWindow('S2l0Y2hlbiBIZWF0IERldGVjdG9y','672')","id":"sensor-15","devIndex":"24VER1","name":"Kitchen Heat Detector","tags":"sensor,fire"},{"state":{"icon":"devStatOK","statusTxt":"Laundry Room Door - Closed\nLast Activity: 8/31 10:01 AM","activityTs":1567260087659},"deprecatedAction":"launchDetailsWindow('TGF1bmRyeSBSb29tIERvb3I=','672')","id":"sensor-5","devIndex":"13VER1","name":"Laundry Room Door","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOK","statusTxt":"Window Basement Bathroom - Closed\nLast Activity: 9/29 11:38 PM","activityTs":1506742723551},"deprecatedAction":"launchDetailsWindow('V2luZG93IEJhc2VtZW50IEJhdGhyb29t','672')","id":"sensor-23","devIndex":"19VER1","name":"Window Basement Bathroom","tags":"sensor,doorWindow"},{"state":{"icon":"devStatOKcamera","statusTxt":"Kitchen Camera\nLast Activity: Today 1:10 PM","activityTs":1575828658216},"deprecatedAction":"openWindow('../portalCamera/portalCamera.jsp#/main/llv/camera-48','imageWindow',100,1,762,733);","id":"camera-48","devIndex":"FBBB1B","name":"Kitchen Camera","tags":"camera,ip"},{"state":{"icon":"devStatOKgarage","statusTxt":"Center Garage - Closed\nLast Activity: Today 12:48 PM","activityTs":1575827334916},"deprecatedAction":"if(gA){gA.logView('Summary page: quick control window was opened for barrier-operator');}openQuickControlWindow( '../quickcontrol/controlBarrier.jsp?fi=Q2VudGVyIEdhcmFnZQ==&id=15','controlwindow','toolbar=no,resizable=no,scrollbars=no,left=300,top=250,screenX=200,screenY=200,width=350,height=235');","id":"door-62","devIndex":"15","name":"Center Garage","tags":"barrier,zw"},{"state":{"icon":"devStatOKlock","statusTxt":"Door Lock - Locked\nLast Activity: Today 12:47 PM","activityTs":1575827226035},"deprecatedAction":"if(gA){gA.logView('Summary page: quick control window was opened for door-lock');}openQuickControlWindow( '../quickcontrol/controlDoorlock.jsp?fi=RG9vciBMb2Nr&id=13','controlwindow','toolbar=no,resizable=no,scrollbars=no,left=300,top=250,screenX=200,screenY=200,width=350,height=235');","id":"door-75","devIndex":"13","name":"Door Lock","tags":"doorlock,zw"},{"state":{"icon":"devStatOKgarage","statusTxt":"Left Garage - Closed\nLast Activity: Today 12:46 PM","activityTs":1575827216154},"deprecatedAction":"if(gA){gA.logView('Summary page: quick control window was opened for barrier-operator');}openQuickControlWindow( '../quickcontrol/controlBarrier.jsp?fi=TGVmdCBHYXJhZ2U=&id=14','controlwindow','toolbar=no,resizable=no,scrollbars=no,left=300,top=250,screenX=200,screenY=200,width=350,height=235');","id":"door-77","devIndex":"14","name":"Left Garage","tags":"barrier,zw"},{"state":{"icon":"devStatOKgarage","statusTxt":"Right Garage - Closed\nLast Activity: Today 12:47 PM","activityTs":1575827220629},"deprecatedAction":"if(gA){gA.logView('Summary page: quick control window was opened for barrier-operator');}openQuickControlWindow( '../quickcontrol/controlBarrier.jsp?fi=UmlnaHQgR2FyYWdl&id=16','controlwindow','toolbar=no,resizable=no,scrollbars=no,left=300,top=250,screenX=200,screenY=200,width=350,height=235');","id":"door-63","devIndex":"16","name":"Right Garage","tags":"barrier,zw"}],"id":"hvwData","ts":1575828670482}

**Comment by mrjackyliang** [comment]
Closed. Reference to issue #8.
