### ISSUE TITLE
allow changing Device and zone statuses interval

### ISSUE THREAD

**Issue by dknjphomeautomation2** [mrjackyliang/homebridge-adt-pulse#90]
Create a configuration value for the Device and zone statuses fetch interval to change to longer than every 3 seconds.

Add interval to the plugin settings for status interval.

**Comment by mrjackyliang** [comment]
The interval shouldn't be changed because the 3 seconds interval is used by the platform default. If I allow this to be changed, you run the risk of your account and IP being blocked by ADT
