### ISSUE TITLE
Type Error: Cannot read properties of null

### ISSUE THREAD

**Issue by sanperez1964** [mrjackyliang/homebridge-adt-pulse#91]
### Describe the bug:
What do you think the problem relates to?
I cannot get the ADT bridge to work on Hoobs
### Steps to reproduce the bug:
1. The Hoobs Helpdesk referred me to your instructions at: https://github.com/mrjackyliang/homebridge-adt-pulse#readme
2. I followed the instructions exactly step by step
3. None of the ADT devices appear on Hoobs
4. The Hoobs Log reads: Add Pulse Bridge WARNING unhandled rejection: Type Error: Cannot read properties of null (reading 'match')

### Expected behavior:
I expected for the Act Bridge to work after I configured it following your detailed instructions

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]
Mac OS 13.0.01
### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[12/2/2022, 4:29:17 PM] [ADT Pulse] running on linux (arm)
[12/2/2022, 4:29:17 PM] [ADT Pulse] homebridge-adt-pulse v2.1.5
[12/2/2022, 4:29:17 PM] [ADT Pulse] node v16.18.1
[12/2/2022, 4:29:17 PM] [ADT Pulse] homebridge v1.5.0
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
Add Pulse Bridge WARNING unhandled rejection: Type Error: Cannot read properties of null (reading 'match')
```

**Comment by mrjackyliang** [comment]
Hi,

Can you enable debug mode and send me all the logs?

**Comment by sanperez1964** [comment]
Do you mean on Hoobs? How do I do that?

**Comment by mrjackyliang** [comment]
It should be in the plugin settings. The logs should show in HOOBS somewhere. It's like a black screen with white text

**Comment by sanperez1964** [comment]
[log.txt](https://github.com/mrjackyliang/homebridge-adt-pulse/files/10146966/log.txt)

Is this what you are referring to?

**Comment by mrjackyliang** [comment]
Yes, but the plugin is not running in debug mode. I need debug to find the series of events of why this is happening.

**Comment by sanperez1964** [comment]
Hello Jacky. I am trying to figure out how to run Hoobs in debug mode. I have reached out to their help desk, but if you have an easy way to tell me how to do that I'd be happy to try. Thank you.

**Comment by sanperez1964** [comment]
Hi Jacky. Attached please find the logs ran in debug mode. Thank you.
[log.txt](https://github.com/mrjackyliang/homebridge-adt-pulse/files/10149063/log.txt)

**Comment by mrjackyliang** [comment]
These are not debug logs. I believe they're in the plugin settings. You'd have to set that in addition to turning on the debug mode in HOOBS.

Apologize for the misunderstanding. I don't have a HOOBS system, so I cannot really follow through with the how-tos.

**Comment by sanperez1964** [comment]
I can't figure out how to set this in the plugin settings. I rerun the debug logs and they look different from the version I sent to you before. Could this be it?
[log.txt](https://github.com/mrjackyliang/homebridge-adt-pulse/files/10220327/log.txt)

**Comment by mrjackyliang** [comment]
This doesn't look like it either. Your logs are just filled with the Phillips Hue errors. The setting should be Log Level. Set that to 40, and make sure your HOOBS is also set in debug mode.

**Comment by mrjackyliang** [comment]
Going to close this issue since I wasn't able to receive any logs related to this issue. Let me know when you find them and I'll re-open it.
