### ISSUE TITLE
Web portal version 25.0.0-12 detected

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#93]
Doesn’t seam like the plugin is working with the latest adt web update.

**Comment by mrjackyliang** [comment]
Going to test out the plugin this week! I have noticed some slowdowns

**Comment by jmcgwire** [comment]
I also am experiencing the same behavior.  This is a new installation of Homebridge and the ADT plugin.  Verbose logs show the following on a repeated basis:

ADT Pulse: Logging in...
ADT Pulse: Response path -> /myhome/25.0.0-21/access/signin.jsp
ADT Pulse: Response path matches -> true
ADT Pulse: Web portal version -> 25.0.0-21
ADT Pulse: Response path -> /myhome/25.0.0-21/mfa/mfaSignIn.jsp?workflow=challenge
ADT Pulse: Response path matches -> false
ADT Pulse: Login failed.

**Comment by mrjackyliang** [comment]
> Doesn’t seam like the plugin is working with the latest adt web update.

The plugin works fine. Could be a temporary glitch.

**Comment by mrjackyliang** [comment]
> I also am experiencing the same behavior.  This is a new installation of Homebridge and the ADT plugin.  Verbose logs show the following on a repeated basis:
> 
> 
> 
> ADT Pulse: Logging in...
> 
> ADT Pulse: Response path -> /myhome/25.0.0-21/access/signin.jsp
> 
> ADT Pulse: Response path matches -> true
> 
> ADT Pulse: Web portal version -> 25.0.0-21
> 
> ADT Pulse: Response path -> /myhome/25.0.0-21/mfa/mfaSignIn.jsp?workflow=challenge
> 
> ADT Pulse: Response path matches -> false
> 
> ADT Pulse: Login failed.
> 
> 

You need to follow the 2FA directions. It's not possible to use this plugin without having 2FA on anymore.

**Comment by bezhermoso** [comment]
@mrjackyliang I've been experiencing issues recently, could it be related to the new Web Portal version?

Seeing this in Homebridge logs:

```
[1/21/2023, 6:33:17 AM] [ADT Pulse] Security Panel (system-1) changed from "armed stay / all quiet" to "disarmed / all quiet".
[1/21/2023, 7:23:27 AM] [ADT Pulse] An unknown error occurred.
```

I know that doesn't tell much other than things didn't quite work, is there a way more informative logs somewhere?

**Comment by mrjackyliang** [comment]
> @mrjackyliang I've been experiencing issues recently, could it be related to the new Web Portal version?
> 
> 
> 
> Seeing this in Homebridge logs:
> 
> 
> 
> ```
> 
> [1/21/2023, 6:33:17 AM] [ADT Pulse] Security Panel (system-1) changed from "armed stay / all quiet" to "disarmed / all quiet".
> 
> [1/21/2023, 7:23:27 AM] [ADT Pulse] An unknown error occurred.
> 
> ```
> 
> 
> 
> I know that doesn't tell much other than things didn't quite work, is there a way more informative logs somewhere?

I think that's just a random login failure. That happens from time to time and the plugin will self recover from it.

But if you are constantly having issues arming and disarming for long periods at a time and sensors aren't updating then that's a problem. But if it's a downtime for approximately 15 mins, that usually is just a recovery period.

**Comment by bezhermoso** [comment]
@mrjackyliang Ahh. Restarting the child-bridge fixed it. Wasn't clear that it was able to self-heal. That would be a separate issue. Things seems to work better now.

**Comment by mrjackyliang** [comment]
> @mrjackyliang Ahh. Restarting the child-bridge fixed it. Wasn't clear that it was able to self-heal. That would be a separate issue. Things seems to work better now.

Yeah, usually it happens. If it is indeed broken, my guess is that you wouldn't be able to arm/disarm the system, receive sensor updates, or both. And it would be very noticeable if it breaks.
