### ISSUE TITLE
ADT Pulse suddenly has become very slow/delayed to respond in home app. Using Hoobs. All plugins are updated.

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#94]
### Describe the bug:
What do you think the problem relates to?

### Steps to reproduce the bug:
1. 

### The Apple device you are using:
- Device: [e.g. iPhone 11 Pro]
- OS: [e.g. iOS 13.3]

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
[1/1/2020, 0:00:00 PM] [ADT Pulse] running on linux (arm)
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge-adt-pulse v1.0.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] node v12.13.0
[1/1/2020, 0:00:00 PM] [ADT Pulse] homebridge v0.4.50
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
SAMPLE TEXT
```

**Comment by mrjackyliang** [comment]
If the plugin response is slow, check the logs and see if you see any warnings or errors.

If there aren't, usually it is because that the Pulse service is just acting up (aging system) and there's no way to fix it.

**Comment by sptv1** [comment]
ERROR[ADT Pulse Bridge ***@***.*** System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!

**Comment by mrjackyliang** [comment]
Can you get me debug logs prior to this happening? Your configuration needs to be changed to allow debug logs and HOOBS needs to be set to debug logs.

**Comment by sptv1** [comment]
I just changed ADT plugin to debug so I don’t have anything prior to this happening.

Not sure how to set HOOBS to debug.

**Comment by mrjackyliang** [comment]
I think you can follow the directions [here](https://github.com/hoobs-org/HOOBS/issues/709). I personally don't use HOOBS but for me, the Homebridge instance would need to be launched in debug mode. Or simply to say, a restart is required.
