### ISSUE TITLE
Web Portal version 25.0.0-21 detected. Test plugin to ensure system compatibility...

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#95]
### Describe the bug:
Portal slow to respond and warning message showing up

### Steps to reproduce the bug:
1. re-launch homebridge
2. note warning In homebridge logs

### Expected behavior:
portal to function normally. with new version. 

### The Apple device you are using:
Homebridge 1.6.0
homebridge-adt-pulse v2.1.5

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

[2/26/2023, 10:25:05 PM] [ADT Pulse] Web Portal version 25.0.0-21 detected. Test plugin to ensure system compatibility...

**Comment by mrjackyliang** [comment]
Thanks! Will do some testing and release a new version.

**Comment by mdombrowski13** [comment]
Anytime happy to help

**Comment by Fergie2020** [comment]
Getting the same exact issue as stated above.

**Comment by mrjackyliang** [comment]
Shouldn't be a huge issue. The warning is there as a reminder to test the plugin again.

If it's working normally, it should be good!

**Comment by mlw4428** [comment]
> Shouldn't be a huge issue. The warning is there as a reminder to test the plugin again.
> 
> If it's working normally, it should be good!

Mine doesn't seem to be working. It looks like it's logging in, but everything in Homekit fails to complete...arming/disarming for example.

**Comment by mrjackyliang** [comment]
> > Shouldn't be a huge issue. The warning is there as a reminder to test the plugin again.
> > If it's working normally, it should be good!
> 
> Mine doesn't seem to be working. It looks like it's logging in, but everything in Homekit fails to complete...arming/disarming for example. Any chance an update is coming that might fix this?

Can you show me some logs? It seems to be working on my end

**Comment by mrjackyliang** [comment]
I tried it again today, and noticed there was a network glitch. Didn't fix anything here, but clearing the Homebridge logs, and restarting Homebridge seems to work.

At the moment, everything is fine, an update will be posted to just clear out the update warnings, but not sure if I want to invest the time to re-build the entire plugin using TypeScript.
