### ISSUE TITLE
Automation for Arming Away and Arming Stay

### ISSUE THREAD

**Issue by Mattapoisett** [mrjackyliang/homebridge-adt-pulse#96]
Something I would like to be able to do, and have not figured out a way to make it happen. When I arm the system as away, I would like to trigger turning off most of the lights, However, Apple Home does not distinguish between arming away and arming stay/night for ADT.  In the set up for this automation,it only offers action after ADT arms, disarms, or triggers. 

Would it be possible to have Apple Home recognize the difference between arming away and arming stay?

Also, your plug-in offers notification from ADT for arming and disarming the system. Would it be possible to offer a notification when something like the garage door is opening to set-up an automation which is triggered when the garage door is opened?  The ADT Pulse app does send out a notification when the garage door is opened

As for what alternatives I've considered for the arming trigger, would be to set up a scene. However I'd like this to be able to be triggered by arming with a fob by someone who doesn't have access to my Apple Home.

**Comment by mrjackyliang** [comment]
The Home app doesn't support what you want to do, but the Home+ app does.

As for the notifications, they are controlled by Apple, not the plugin.

To link up your garage door, they must not be linked to ADT since the plugin does not offer support for Z-Wave accessories.
