### ISSUE TITLE
Question regarding ADT warnings

### ISSUE THREAD

**Issue by sptv1** [mrjackyliang/homebridge-adt-pulse#99]
I don't know if this is a bug, but I keep getting lots of error messages and warnings with the ADT plugin.  Here's a sample of the logs:

4/29/2023, 6:29:09 AMADT Pulse BridgeERROR[ADT Pulse Bridge 2801@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
4/29/2023, 6:30:52 AMADT Pulse BridgeADT PulseSetting Security Panel (system-1) status from disarmed to off...
4/29/2023, 6:30:52 AMADT Pulse BridgeADT PulseWARNINGAlready set to off. Cannot set from disarmed to off.
4/29/2023, 6:30:55 AMADT Pulse BridgeERROR[ADT Pulse Bridge 2801@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!
4/29/2023, 6:31:28 AMADT Pulse BridgeADT PulseSetting Security Panel (system-1) status from disarmed to off...
4/29/2023, 6:31:28 AMADT Pulse BridgeADT PulseWARNINGAlready set to off. Cannot set from disarmed to off.
4/29/2023, 6:31:31 AMADT Pulse BridgeERROR[ADT Pulse Bridge 2801@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Security Panel' was slow to respond!

**Comment by mrjackyliang** [comment]
Don't think this is a bug. Seems to me it is just a slow response from the ADT Pulse website.

This will happen from time to time, or if your network can't establish a fast enough connection to the portal.

If you cannot arm/disarm, then that itself is a bug.
